Repository istio-ecosystem/sail-operator, pull requests merged in 2024-11, with the labels that each got.

#464 Fixing issue with missing istiod-remote chart when adding new versions
  hack/update-istio.sh
Labels: size/XS

#465 Update version reference in docs guide
  docs/README.md
Labels: size/L

#461 Remove RemoteIstio resource
  PROJECT
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiocni_types.go
  api/v1alpha1/istiorevision_types.go
  api/v1alpha1/remoteistio_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/sailoperator.io_istiocnis.yaml
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  bundle/manifests/sailoperator.io_remoteistios.yaml
  chart/crds/sailoperator.io_istiocnis.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_remoteistios.yaml
  chart/samples/remoteistio-sample.yaml
  cmd/main.go
  controllers/istio/istio_controller.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/remoteistio/remoteistio_controller.go
  controllers/remoteistio/remoteistio_controller_test.go
  controllers/webhook/webhook_controller.go
  controllers/webhook/webhook_controller_test.go
  docs/README.md
  docs/api-reference/sailoperator.io.md
  hack/download-charts.sh
  hack/update-profiles-list.sh
  hack/update-version-list.sh
  pkg/constants/constants.go
  pkg/revision/reconcile.go
  pkg/revision/reconcile_test.go
  pkg/revision/remote.go
  pkg/version/semverutils.go
  pkg/version/semverutils_test.go
  resources/latest/profiles/remote.yaml
  resources/v1.21.6/profiles/remote.yaml
  resources/v1.22.5/profiles/remote.yaml
  resources/v1.23.2/profiles/remote.yaml
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/integration/api/istio_test.go
  tests/integration/api/istiorevision_test.go
  tests/integration/api/suite_test.go
Labels: size/XXL

#470 Clean up istiod-gateway-controller-istio-system ClusterRole & Binding in primary-remote test
  tests/e2e/multicluster/multicluster_primaryremote_test.go
Labels: size/XS

#469 Implement temporary hack to prevent removal of pull secrets added by external controllers
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/predicate/predicate.go
  tests/integration/api/istiocni_test.go
  tests/integration/api/istiorevision_test.go
Labels: size/L

#212 enhancements: add SEP for revision tag support
  enhancements/SEP2-revision-tags.md
Labels: size/L

#473 Remove redundant variable copying in for loops
  common/config/.golangci.yml
  controllers/istio/istio_controller_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/integration/api/istio_test.go
Labels: size/S

#483 Centralize the way the sample apps yaml are being set to be deployed
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/L

#487 Update e2e Documentation with env var to set sample yaml files
  tests/e2e/README.md
Labels: size/S
