Repository istio-ecosystem/sail-operator, pull requests merged in 2024-12, with the labels that each got.

#506 Add documentation for running multiple meshes on a single cluster
  docs/README.md
Labels: size/L

#481 Implement API and CRD for ztunnel component
  PROJECT
  api/v1alpha1/values_types_extra.go
  api/v1alpha1/ztunnel_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/sailoperator.io_ztunnels.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
  docs/api-reference/sailoperator.io.md
Labels: size/XXL, ok-to-test, ambient

#512 Implement ztunnel controller in Sail Operator
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/samples/ambient/istio-sample.yaml
  chart/samples/ambient/istiocni-sample.yaml
  chart/samples/ambient/istioztunnel-sample.yaml
  chart/templates/rbac/role.yaml
  cmd/main.go
  controllers/ztunnel/ztunnel_controller.go
  controllers/ztunnel/ztunnel_controller_test.go
Labels: size/XL

#517 Bump version to 0.3.0
  .github/workflows/release.yaml
  Makefile.core.mk
  bundle.Dockerfile
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  chart/Chart.yaml
  chart/values.yaml
Labels: size/S

#525 Add note for cni versions compatibility
  docs/README.md
Labels: size/XS

#533 Fix undeploy when using Ambient mode
  Makefile.core.mk
Labels: size/XS

#522 Fix issue-management page
  ISSUE-MANAGEMENT.md
Labels: size/XS

#539 Remove unneeded securityContext fields from multicluster manifests
  docs/multicluster/controlplane-gateway.yaml
  docs/multicluster/east-west-gateway-net1.yaml
  docs/multicluster/east-west-gateway-net2.yaml
Labels: size/S

#544 Skip namespace while deleting cluster scoped resources
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_test.go
Labels: size/XS
