Repository istio-ecosystem/sail-operator, pull requests merged in 2024-08, with the labels that each got.

#245 Fix running e2e tests on OCP with custom images
  tests/e2e/common-operator-integ-suite.sh
Labels: size/XS

#246 Simplify validatingwebhookconfig predicate in IstioRevision controller
  controllers/istiorevision/istiorevision_controller.go
Labels: size/M

#244 Use reflect.New instead of DeepCopy in StandardReconciler
  controllers/istio/istio_controller.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
Labels: size/S

#247 Fix instructions README url
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
Labels: size/XS

#225 docs: explain API concepts
  docs/README.md
Labels: size/M

#252 docs: make sure we use "Sail Operator" notation everywhere
  docs/README.md
Labels: size/XS

#255 Disabling broken shellcheck
  common/scripts/check_clean_repo.sh
Labels: size/XS

#257 Add descriptions to fields in CNIGlobalConfig
  api/v1alpha1/values_types_extra.go
  bundle/manifests/operator.istio.io_istiocnis.yaml
  chart/crds/operator.istio.io_istiocnis.yaml
  docs/api-reference/operator.istio.io.md
Labels: size/M

#254 Fix issues identified during API review
  Makefile.core.mk
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/values_types_extra.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istiocnis.yaml
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istiocnis.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  docs/api-reference/operator.istio.io.md
  hack/api_transformer/transform.yaml
Labels: size/XXL

#258 Generate API from versions defined in go.mod
  Makefile.core.mk
  hack/api_transformer/main.go
  hack/api_transformer/transform.yaml
Labels: size/M

#243 Add relatedImages to ClusterServiceVersion
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  hack/patch-csv.sh
Labels: size/L

#259 Rename `addTags` to `addComments` in API transformer
  hack/api_transformer/main.go
  hack/api_transformer/transform.yaml
Labels: size/S

#262 Fix errors in api reference doc
  Makefile.core.mk
  docs/api-reference/operator.istio.io.md
Labels: size/XXL

#260 Generate CNIGlobalConfig from GlobalConfig automatically
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/values_types_extra.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istiocnis.yaml
  chart/crds/operator.istio.io_istiocnis.yaml
  docs/api-reference/operator.istio.io.md
  hack/api_transformer/main.go
  hack/api_transformer/transform.yaml
Labels: size/L

#264 Add field values.experimental to API
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  docs/api-reference/operator.istio.io.md
  hack/api_transformer/main.go
  hack/api_transformer/transform.yaml
Labels: size/M

#269 api_transformer: use `go env` to detect mod cache dir
  hack/api_transformer/main.go
Labels: size/XS

#270 Ensure `make gen-check` works when go mod cache is empty
  Makefile.core.mk
  go.mod
  go.sum
  tools.go
Labels: size/M

#272 Add `RemoteIstio` to API concepts in docs
  docs/README.md
Labels: size/M

#277 Fix RemoteIstio
  hack/update-istio.sh
  resources/latest/charts/istiod-remote/Chart.yaml
  resources/latest/charts/istiod-remote/NOTES.txt
  resources/latest/charts/istiod-remote/files/gateway-injection-template.yaml
  resources/latest/charts/istiod-remote/files/injection-template.yaml
  resources/latest/charts/istiod-remote/files/profile-ambient.yaml
  resources/latest/charts/istiod-remote/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/istiod-remote/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/istiod-remote/files/profile-compatibility-version-1.23.yaml
  resources/latest/charts/istiod-remote/files/profile-demo.yaml
  resources/latest/charts/istiod-remote/files/profile-openshift-ambient.yaml
  resources/latest/charts/istiod-remote/files/profile-openshift.yaml
  resources/latest/charts/istiod-remote/files/profile-preview.yaml
  resources/latest/charts/istiod-remote/files/profile-stable.yaml
  resources/latest/charts/istiod-remote/templates/_helpers.tpl
  resources/latest/charts/istiod-remote/templates/clusterrole.yaml
  resources/latest/charts/istiod-remote/templates/clusterrolebinding.yaml
  resources/latest/charts/istiod-remote/templates/configmap.yaml
  resources/latest/charts/istiod-remote/templates/crd-all.gen.yaml
  resources/latest/charts/istiod-remote/templates/default.yaml
  resources/latest/charts/istiod-remote/templates/defaultrevisionvalidatingadmissionpolicy.yaml
  resources/latest/charts/istiod-remote/templates/endpoints.yaml
  resources/latest/charts/istiod-remote/templates/istiod-injector-configmap.yaml
  resources/latest/charts/istiod-remote/templates/mutatingwebhook.yaml
  resources/latest/charts/istiod-remote/templates/reader-clusterrole.yaml
  resources/latest/charts/istiod-remote/templates/reader-clusterrolebinding.yaml
  resources/latest/charts/istiod-remote/templates/reader-serviceaccount.yaml
  resources/latest/charts/istiod-remote/templates/role.yaml
  resources/latest/charts/istiod-remote/templates/rolebinding.yaml
  resources/latest/charts/istiod-remote/templates/serviceaccount.yaml
  resources/latest/charts/istiod-remote/templates/services.yaml
  resources/latest/charts/istiod-remote/templates/validatingadmissionpolicy.yaml
  resources/latest/charts/istiod-remote/templates/validatingwebhookconfiguration.yaml
  resources/latest/charts/istiod-remote/templates/zzy_descope_legacy.yaml
  resources/latest/charts/istiod-remote/templates/zzz_profile.yaml
  resources/latest/charts/istiod-remote/values.yaml
  versions.yaml
Labels: size/XXL

#276 Ensure update-profiles-list.sh updates profiles in RemoteIstio
  api/v1alpha1/remoteistio_types.go
  bundle/manifests/operator.istio.io_remoteistios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/crds/operator.istio.io_remoteistios.yaml
  docs/api-reference/operator.istio.io.md
  hack/update-profiles-list.sh
Labels: size/S, cherrypick/release-0.1

#291 Fix proxy related image
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  hack/patch-csv.sh
Labels: size/M

#293 Remove cyclic dependency between `bundle` and `gen`
  Makefile.core.mk
Labels: size/XS

#295 Run `make update-common`
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS

#298 Ensure controller-gen make target honors CONTROLLER_TOOLS_VERSION
  Makefile.core.mk
Labels: size/XS

#299 Don't install CRDs when reconciling RemoteIstio
  hack/download-charts.sh
  resources/latest/charts/istiod-remote/templates/crd-all.gen.yaml
  resources/v1.23.0/charts/istiod-remote/templates/crd-all.gen.yaml
Labels: size/XS

#292 Change CSV annotations to `images.<version>.<imageName>`
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  hack/patch-csv.sh
Labels: size/M

#294 Remove yq unique
  hack/patch-csv.sh
Labels: size/XS

#300 Don't watch Secrets and EnvoyFilters in istiorevision controller
  controllers/istiorevision/istiorevision_controller.go
Labels: size/XS

#301 Lint-watches now also checks if controller watches kinds not present in the charts
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  hack/lint-watches.sh
Labels: size/M

#297 Issue 230: adding bookinfo deploy to e2e framework
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/L

#302 [release-0.1] Issue 230: adding bookinfo deploy to e2e framework
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/L, release-notes-none

#307 [release-0.1] Add missing gen-all-except-bundle target
  Makefile.core.mk
Labels: size/XS, release-notes-none

#305 [release-0.1] Updating common files to be based on release-1.23 branch
  .devcontainer/devcontainer.json
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/S

#310 Add `operator-chart` target
  Makefile.core.mk
  chart/values.yaml
Labels: size/S, cherrypick/release-0.1

#311 [release-0.1] Add `operator-chart` target
  Makefile.core.mk
  chart/values.yaml
Labels: size/S, release-notes-none

#317 Remove old API generator
  Makefile.core.mk
  hack/patch-istio-crd.sh
Labels: size/L

#318 Fetch Istio CRDs from Istio version specified in go.mod
  Makefile.core.mk
  hack/extract-istio-crds.sh
  pkg/test/util/supportedversion/supportedversion.go
  versions.yaml
Labels: size/S

#320 [release-0.1] Fetch Istio CRDs from Istio version specified in go.mod (#318)
  Makefile.core.mk
  bundle/manifests/extensions.istio.io_wasmplugins.yaml
  bundle/manifests/networking.istio.io_destinationrules.yaml
  bundle/manifests/networking.istio.io_envoyfilters.yaml
  bundle/manifests/networking.istio.io_gateways.yaml
  bundle/manifests/networking.istio.io_proxyconfigs.yaml
  bundle/manifests/networking.istio.io_serviceentries.yaml
  bundle/manifests/networking.istio.io_sidecars.yaml
  bundle/manifests/networking.istio.io_virtualservices.yaml
  bundle/manifests/networking.istio.io_workloadentries.yaml
  bundle/manifests/networking.istio.io_workloadgroups.yaml
  bundle/manifests/security.istio.io_authorizationpolicies.yaml
  bundle/manifests/security.istio.io_peerauthentications.yaml
  bundle/manifests/security.istio.io_requestauthentications.yaml
  bundle/manifests/telemetry.istio.io_telemetries.yaml
  chart/crds/extensions.istio.io_wasmplugins.yaml
  chart/crds/networking.istio.io_destinationrules.yaml
  chart/crds/networking.istio.io_envoyfilters.yaml
  chart/crds/networking.istio.io_gateways.yaml
  chart/crds/networking.istio.io_proxyconfigs.yaml
  chart/crds/networking.istio.io_serviceentries.yaml
  chart/crds/networking.istio.io_sidecars.yaml
  chart/crds/networking.istio.io_virtualservices.yaml
  chart/crds/networking.istio.io_workloadentries.yaml
  chart/crds/networking.istio.io_workloadgroups.yaml
  chart/crds/security.istio.io_authorizationpolicies.yaml
  chart/crds/security.istio.io_peerauthentications.yaml
  chart/crds/security.istio.io_requestauthentications.yaml
  chart/crds/telemetry.istio.io_telemetries.yaml
  hack/extract-istio-crds.sh
  pkg/test/util/supportedversion/supportedversion.go
  versions.yaml
Labels: size/XXL

#316 Improvements for RC releases
  Makefile.core.mk
Labels: size/S, cherrypick/release-0.1

#322 [release-0.1] Improvements for RC releases (#316)
  Makefile.core.mk
Labels: size/S

#313 Issue 296: Adding OLM deploy for operator e2e
  Makefile.core.mk
  tests/e2e/README.md
  tests/e2e/common-operator-integ-suite.sh
  tests/e2e/config/default.yaml
Labels: size/M, cherrypick/release-0.1

#323 [release-0.1] Issue 296: Adding OLM deploy for operator e2e
  Makefile.core.mk
  tests/e2e/README.md
  tests/e2e/common-operator-integ-suite.sh
  tests/e2e/config/default.yaml
Labels: size/M, release-notes-none

#326 Fix OLM test setup
  tests/e2e/common-operator-integ-suite.sh
Labels: size/XS

#157 Add docs for multi-cluster install
  docs/README.md
  docs/multicluster/east-west-gateway-net1.yaml
  docs/multicluster/east-west-gateway-net2.yaml
  docs/multicluster/expose-istiod.yaml
  docs/multicluster/expose-services.yaml
  docs/multicluster/setup-multi-primary.sh
Labels: size/XXL, cherrypick/release-0.1

#325 docs: add section on migrating from in-cluster operator
  docs/README.md
Labels: size/M
