Repository istio-ecosystem/sail-operator, pull requests merged in 2024-07, with the labels that each got.

#186 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#188 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#189 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#187 Add user docs for addons
  docs/README.md
Labels: size/L

#190 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/values.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/values.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/gateway-injection-template.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/templates/daemonset.yaml
  resources/latest/charts/ztunnel/templates/rbac.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#193 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/kube-gateway.yaml
  resources/latest/charts/istiod/files/waypoint.yaml
  resources/latest/charts/istiod/templates/istiod-injector-configmap.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#194 Remove outdated comments from Dockerfile
  Dockerfile
Labels: size/XS

#196 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/daemonset.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#200 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/waypoint.yaml
  resources/latest/charts/istiod/templates/clusterrole.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#191 Add enhancements/ directory
  enhancements/README.md
  enhancements/SEP0-template.md
  enhancements/SEP1-enhancement-process.md
  enhancements/diagrams/README.md
Labels: size/M

#201 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/templates/zzz_profile.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/zzz_profile.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/templates/zzz_profile.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/templates/zzz_profile.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/templates/zzz_profile.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#203 Add helm-publish make target
  Makefile.core.mk
Labels: size/S

#205 Update Redme with enhancement process information
  README.md
  enhancements/SEP1-enhancement-process.md
Labels: size/S

#208 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/templates/_helpers.tpl
  resources/latest/charts/ztunnel/templates/daemonset.yaml
  resources/latest/charts/ztunnel/templates/rbac.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#213 Update debug e2e
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/M

#214 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#215 [release-0.1] Update debug e2e
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/M, release-notes-none

#223 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/injection-template.yaml
  resources/latest/charts/istiod/templates/NOTES.txt
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#226 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/configmap-cni.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#228 Fix occurrences of "sail-operator" and spelling/grammar in docs
  CONTRIBUTING.md
  ISSUE-MANAGEMENT.md
  README.md
  SECURITY.md
  bundle/README.md
  docs/README.md
  enhancements/README.md
  enhancements/SEP0-template.md
  enhancements/SEP1-enhancement-process.md
  hack/operatorhub/operatorhub-pr-template.md
  pkg/reconciler/reconciler.go
  tests/e2e/README.md
  tests/integration/README.md
Labels: size/L

#231 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  Makefile
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/injection-template.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/istiod/templates/deployment.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#233 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/configmap-cni.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#234 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/waypoint.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#235 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/files/profile-demo.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-demo.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-demo.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/profile-demo.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-demo.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#238 Add option to log events that cause resources to be enqueued
  cmd/main.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/enqueuelogger/queue.go
  pkg/enqueuelogger/wrapper.go
Labels: size/L

#237 Add make target to generate api reference documentation
  Makefile.core.mk
  README.md
  docs/README.md
  docs/api-reference/operator.istio.io.md
  go.mod
  go.sum
  hack/api-docs/config.yaml
Labels: size/XXL

#229 Update Sail Operator cli instructions
  README.md
  docs/README.md
Labels: size/M

#241 Hide some fields from the API reference docs
  Makefile.core.mk
  api/v1alpha1/values_types.gen.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  docs/api-reference/operator.istio.io.md
  hack/api-docs/config.yaml
  hack/api-docs/templates/markdown/gv_details.tpl
  hack/api-docs/templates/markdown/gv_list.tpl
  hack/api-docs/templates/markdown/type.tpl
  hack/api-docs/templates/markdown/type_members.tpl
  hack/api_transformer/main.go
Labels: size/XL

#242 API reference docs: replace tab tags for headings
  api/v1alpha1/values_types.gen.go
  docs/api-reference/operator.istio.io.md
  hack/api_transformer/main.go
Labels: size/M
