Repository istio-ecosystem/sail-operator, pull requests merged in 2024-04, with the labels that each got.

#7 Automator: Update dependencies in istio-ecosystem/sail-operator@pre-main
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/deployment.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#9 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/files/profile-ambient.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/base/files/profile-demo.yaml
  resources/latest/charts/base/files/profile-openshift-ambient.yaml
  resources/latest/charts/base/files/profile-openshift.yaml
  resources/latest/charts/base/files/profile-preview.yaml
  resources/latest/charts/base/templates/zzz_profile.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-ambient.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/cni/files/profile-demo.yaml
  resources/latest/charts/cni/files/profile-openshift-ambient.yaml
  resources/latest/charts/cni/files/profile-openshift.yaml
  resources/latest/charts/cni/files/profile-preview.yaml
  resources/latest/charts/cni/templates/zzz_profile.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/README.md
  resources/latest/charts/gateway/files/profile-ambient.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/gateway/files/profile-demo.yaml
  resources/latest/charts/gateway/files/profile-openshift-ambient.yaml
  resources/latest/charts/gateway/files/profile-openshift.yaml
  resources/latest/charts/gateway/files/profile-preview.yaml
  resources/latest/charts/gateway/templates/deployment.yaml
  resources/latest/charts/gateway/templates/zzz_profile.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/profile-ambient.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/istiod/files/profile-demo.yaml
  resources/latest/charts/istiod/files/profile-openshift-ambient.yaml
  resources/latest/charts/istiod/files/profile-openshift.yaml
  resources/latest/charts/istiod/files/profile-preview.yaml
  resources/latest/charts/istiod/templates/reader-clusterrole.yaml
  resources/latest/charts/istiod/templates/zzz_profile.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-ambient.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/ztunnel/files/profile-demo.yaml
  resources/latest/charts/ztunnel/files/profile-openshift-ambient.yaml
  resources/latest/charts/ztunnel/files/profile-openshift.yaml
  resources/latest/charts/ztunnel/files/profile-preview.yaml
  resources/latest/charts/ztunnel/templates/zzz_profile.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#10 Update the Readme file
  README.md
Labels: size/M, ok-to-test

#11 Centralize common reconciler code
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
Labels: size/XL

#12 Rename XyzReconciler to Reconciler
  cmd/main.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  tests/integration/api/suite_test.go
Labels: size/L

#13 Remove unused code
  tests/e2e/operator/util/kubectl/kubectl.go
Labels: size/M

#15 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
  go.mod
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/files/profile-ambient.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/base/files/profile-demo.yaml
  resources/latest/charts/base/files/profile-openshift-ambient.yaml
  resources/latest/charts/base/files/profile-openshift.yaml
  resources/latest/charts/base/files/profile-preview.yaml
  resources/latest/charts/base/templates/zzz_profile.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-ambient.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/cni/files/profile-demo.yaml
  resources/latest/charts/cni/files/profile-openshift-ambient.yaml
  resources/latest/charts/cni/files/profile-openshift.yaml
  resources/latest/charts/cni/files/profile-preview.yaml
  resources/latest/charts/cni/templates/zzz_profile.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/README.md
  resources/latest/charts/gateway/files/profile-ambient.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/gateway/files/profile-demo.yaml
  resources/latest/charts/gateway/files/profile-openshift-ambient.yaml
  resources/latest/charts/gateway/files/profile-openshift.yaml
  resources/latest/charts/gateway/files/profile-preview.yaml
  resources/latest/charts/gateway/templates/deployment.yaml
  resources/latest/charts/gateway/templates/zzz_profile.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/profile-ambient.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/istiod/files/profile-demo.yaml
  resources/latest/charts/istiod/files/profile-openshift-ambient.yaml
  resources/latest/charts/istiod/files/profile-openshift.yaml
  resources/latest/charts/istiod/files/profile-preview.yaml
  resources/latest/charts/istiod/templates/reader-clusterrole.yaml
  resources/latest/charts/istiod/templates/zzz_profile.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-ambient.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/ztunnel/files/profile-demo.yaml
  resources/latest/charts/ztunnel/files/profile-openshift-ambient.yaml
  resources/latest/charts/ztunnel/files/profile-openshift.yaml
  resources/latest/charts/ztunnel/files/profile-preview.yaml
  resources/latest/charts/ztunnel/templates/zzz_profile.yaml
  resources/latest/charts/ztunnel/values.yaml
  resources/latest/profiles/external.yaml
  versions.yaml
Labels: auto-merge, size/L

#21 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/telemetry.istio.io_telemetries.yaml
  chart/crds/telemetry.istio.io_telemetries.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/crds/crd-all.gen.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/XL

#23 Remove the patch that deleted fixed UIDs from istiod charts
  hack/download-charts.sh
Labels: size/XS, cleanup/refactor

#24 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/extensions.istio.io_wasmplugins.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/crds/extensions.istio.io_wasmplugins.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/crds/crd-all.gen.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/templates/clusterrole.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#26 Use the `quote` function to properly escape CSV annotations
  chart/templates/olm/clusterserviceversion.yaml
Labels: size/XS

#27 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/files/profile-ambient.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-ambient.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-ambient.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/profile-ambient.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-ambient.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#28 Wrap errors
  go.mod
  hack/api_transformer/main.go
  pkg/helm/chartmanager.go
  pkg/helm/values.go
  pkg/kube/finalizers.go
  pkg/profiles/profiles.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/util/client/client.go
  tests/e2e/util/helm/helm.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/M

#31 Add Debug information when e2e Test run Fails
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/M, ok-to-test

#32 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#33 Add `operator-name` target
  Makefile.core.mk
Labels: size/XS

#34 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/files/profile-ambient.yaml
  resources/latest/charts/base/files/profile-openshift-ambient.yaml
  resources/latest/charts/base/files/profile-openshift.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-ambient.yaml
  resources/latest/charts/cni/files/profile-openshift-ambient.yaml
  resources/latest/charts/cni/files/profile-openshift.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-ambient.yaml
  resources/latest/charts/gateway/files/profile-openshift-ambient.yaml
  resources/latest/charts/gateway/files/profile-openshift.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/profile-ambient.yaml
  resources/latest/charts/istiod/files/profile-openshift-ambient.yaml
  resources/latest/charts/istiod/files/profile-openshift.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-ambient.yaml
  resources/latest/charts/ztunnel/files/profile-openshift-ambient.yaml
  resources/latest/charts/ztunnel/files/profile-openshift.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#35 Update bot username to openshift-service-mesh-bot
  Makefile.core.mk
Labels: size/XS

#36 Create namespace if it doesn't exist in README example
  README.md
Labels: size/XS, ok-to-test

#25 Centralize handling of conflicts and other common errors
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
Labels: size/L, cleanup/refactor

#37 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/extensions.istio.io_wasmplugins.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/crds/extensions.istio.io_wasmplugins.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/crds/crd-all.gen.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#40 Update PROJECT file
  PROJECT
Labels: size/S

#41 Fix debug info in e2e tests
  tests/e2e/util/common/e2e_utils.go
Labels: size/XS

#42 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/templates/clusterrole.yaml
  resources/latest/charts/istiod/templates/deployment.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#43 Add defaulting for Istio and IstioCNI resources
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiocni_types.go
  bundle/manifests/operator.istio.io_istiocnis.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istiocnis.yaml
  chart/crds/operator.istio.io_istios.yaml
  hack/update-version-list.sh
  pkg/test/util/supportedversion/supportedversion.go
  tests/e2e/controlplane/control_plane_test.go
Labels: size/L

#44 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/extensions.istio.io_wasmplugins.yaml
  bundle/manifests/networking.istio.io_envoyfilters.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/security.istio.io_authorizationpolicies.yaml
  bundle/manifests/security.istio.io_requestauthentications.yaml
  bundle/manifests/telemetry.istio.io_telemetries.yaml
  chart/crds/extensions.istio.io_wasmplugins.yaml
  chart/crds/networking.istio.io_envoyfilters.yaml
  chart/crds/security.istio.io_authorizationpolicies.yaml
  chart/crds/security.istio.io_requestauthentications.yaml
  chart/crds/telemetry.istio.io_telemetries.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/crds/crd-all.gen.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#52 Improve e2e debug info
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/M

#48 Fix flaky e2e tests
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/S

#51 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#50 Update read me for e2e test
  tests/e2e/README.md
  tests/integration/README.md
Labels: size/L

#53 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/templates/NOTES.txt
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/NOTES.txt
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/templates/NOTES.txt
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/templates/NOTES.txt
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#56 Create sail-operator namespace on `make deploy-openshift`
  Makefile.core.mk
Labels: size/XS

#57 Deploy IstioCNI on `make deploy-example-openshift`
  Makefile.core.mk
Labels: size/XS

#58 Add minor information to bundle readme
  bundle/README.md
Labels: size/XS

#59 Fix retrieving of DaemonSet logs in e2e tests
  tests/e2e/util/common/e2e_utils.go
Labels: size/XS

#60 e2e tests: skip deletion of operator namespace on OCP
  tests/e2e/controlplane/control_plane_test.go
Labels: size/XS

#61 Small cleanup of applyOverrides()
  controllers/istio/istio_controller.go
Labels: size/XS

#62 Introduce validation errors
  controllers/istio/istio_controller.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/profiles/profiles.go
  pkg/reconciler/errors.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
Labels: size/M

#63 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/files/profile-ambient.yaml
  resources/latest/charts/base/files/profile-openshift-ambient.yaml
  resources/latest/charts/base/templates/default.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-ambient.yaml
  resources/latest/charts/cni/files/profile-openshift-ambient.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-ambient.yaml
  resources/latest/charts/gateway/files/profile-openshift-ambient.yaml
  resources/latest/charts/gateway/templates/deployment.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/grpc-agent.yaml
  resources/latest/charts/istiod/files/profile-ambient.yaml
  resources/latest/charts/istiod/files/profile-openshift-ambient.yaml
  resources/latest/charts/istiod/templates/autoscale.yaml
  resources/latest/charts/istiod/templates/configmap-jwks.yaml
  resources/latest/charts/istiod/templates/configmap.yaml
  resources/latest/charts/istiod/templates/deployment.yaml
  resources/latest/charts/istiod/templates/istiod-injector-configmap.yaml
  resources/latest/charts/istiod/templates/mutatingwebhook.yaml
  resources/latest/charts/istiod/templates/poddisruptionbudget.yaml
  resources/latest/charts/istiod/templates/revision-tags.yaml
  resources/latest/charts/istiod/templates/service.yaml
  resources/latest/charts/istiod/templates/validatingwebhookconfiguration.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-ambient.yaml
  resources/latest/charts/ztunnel/files/profile-openshift-ambient.yaml
  resources/latest/charts/ztunnel/templates/NOTES.txt
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#65 Ensure control plane is deployed immediately when the target namespace is created
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/kube/key.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/util/client/client.go
  tests/e2e/util/common/e2e_utils.go
  tests/integration/api/istiorevision_test.go
Labels: size/L

#66 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/kube-gateway.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#69 Update SetDefaultEventuallyTimeout for e2e test
  tests/e2e/controlplane/control_plane_test.go
Labels: size/XS

#70 Ensure CI highlights failure in lint-watches.sh
  hack/lint-watches.sh
Labels: size/XS

#71 Make lint-watches ignore ValidatingAdmissionPolicy(Binding)
  controllers/istiorevision/istiorevision_controller.go
Labels: size/XS

#72 Ensure update-istio.sh updates version field in versions.yaml
  hack/update-istio.sh
Labels: size/XS

#68 Wrap errors to provide context
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  pkg/helm/values.go
  pkg/profiles/profiles.go
  pkg/reconciler/errors.go
Labels: size/L

#73 Make bundle generation work during merges
  Makefile.core.mk
Labels: size/XS

#76 Refactor
  pkg/reconciler/reconciler.go
Labels: size/S

#67 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  Makefile.core.mk
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiocni_types.go
  bundle/manifests/extensions.istio.io_wasmplugins.yaml
  bundle/manifests/networking.istio.io_destinationrules.yaml
  bundle/manifests/networking.istio.io_envoyfilters.yaml
  bundle/manifests/networking.istio.io_gateways.yaml
  bundle/manifests/networking.istio.io_proxyconfigs.yaml
  bundle/manifests/networking.istio.io_serviceentries.yaml
  bundle/manifests/networking.istio.io_sidecars.yaml
  bundle/manifests/networking.istio.io_virtualservices.yaml
  bundle/manifests/networking.istio.io_workloadentries.yaml
  bundle/manifests/networking.istio.io_workloadgroups.yaml
  bundle/manifests/operator.istio.io_istiocnis.yaml
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/telemetry.istio.io_telemetries.yaml
  chart/crds/extensions.istio.io_wasmplugins.yaml
  chart/crds/networking.istio.io_destinationrules.yaml
  chart/crds/networking.istio.io_envoyfilters.yaml
  chart/crds/networking.istio.io_gateways.yaml
  chart/crds/networking.istio.io_proxyconfigs.yaml
  chart/crds/networking.istio.io_serviceentries.yaml
  chart/crds/networking.istio.io_sidecars.yaml
  chart/crds/networking.istio.io_virtualservices.yaml
  chart/crds/networking.istio.io_workloadentries.yaml
  chart/crds/networking.istio.io_workloadgroups.yaml
  chart/crds/operator.istio.io_istiocnis.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  chart/crds/telemetry.istio.io_telemetries.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/crds/crd-all.gen.yaml
  resources/latest/charts/base/files/profile-stable.yaml
  resources/latest/charts/base/templates/validatingadmissionpolicy.yaml
  resources/latest/charts/base/values.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-stable.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-stable.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/profile-stable.yaml
  resources/latest/charts/istiod/templates/validatingadmissionpolicy.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-stable.yaml
  resources/latest/charts/ztunnel/values.yaml
  resources/latest/profiles/stable.yaml
  versions.yaml
Labels: size/XXL, auto-merge

#77 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#79 Remove unused fields from API (BaseConfig)
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  hack/api_transformer/transform.yaml
Labels: size/M

#80 Deploy CNI DaemonSet immediately when namespace is created
  controllers/istiocni/istiocni_controller.go
  tests/integration/api/istiocni_test.go
  tests/integration/api/istiorevision_test.go
Labels: size/L

#81 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#82 Remove duplicates of oneMinuteAgo()
  controllers/istio/istio_controller_test.go
  pkg/reconciler/reconciler_test.go
  pkg/test/testtime/time.go
Labels: size/M

#83 Introduce a central way to get the project's root directory
  pkg/config/config.go
  pkg/test/environment.go
  pkg/test/project/project.go
  pkg/test/util/supportedversion/supportedversion.go
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/operator/operator_suite_test.go
  tests/integration/api/suite_test.go
Labels: size/M

#89 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/grpc-agent.yaml
  resources/latest/charts/istiod/files/injection-template.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#88 Don't log error when namespace is being deleted
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  pkg/validation/namespace.go
  pkg/validation/namespace_test.go
Labels: size/L

#93 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/templates/validatingadmissionpolicy.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/templates/validatingadmissionpolicy.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#95 Fix pushing olm bundle
  Makefile.core.mk
Labels: size/XS

#99 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/daemonset.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge
