Repository istio-ecosystem/sail-operator, pull requests merged in 2024-10, with the labels that each got.

#377 Fix broken url for sample gateway
  docs/common/create-and-configure-gateways.md
Labels: size/XS

#349 Update/Fix Istioctl links and docs
  docs/README.md
  docs/common/install-istioctl-tool.md
Labels: size/S

#378 Adding default value for IP_FAMILY
  tests/e2e/common-operator-integ-suite.sh
Labels: size/XS

#384 Fix error handling in deployBookinfo
  tests/e2e/controlplane/control_plane_test.go
Labels: size/XS

#383 Implement e2e dualStack data plane tests
  tests/e2e/dualstack/dualstack_suite_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/L

#392 Clean up code
  controllers/istio/istio_controller_test.go
  pkg/kube/key.go
  pkg/reconciler/reconciler.go
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_suite_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/operator/operator_suite_test.go
  tests/e2e/util/certs/certs.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/istioctl/istioctl.go
Labels: size/M

#391 Simplify supportedversion.go and add unit tests
  go.mod
  hack/update-istio.sh
  pkg/test/util/supportedversion/supportedversion.go
  pkg/test/util/supportedversion/supportedversion_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/util/common/e2e_utils.go
  versions.yaml
Labels: size/L

#385 Add Helm artifacts publish automation
  .github/workflows/helm.yaml
  Makefile.core.mk
  hack/helm-artifacts.sh
Labels: size/L

#396 Don't add istiod-remote chart when updating latest version
  hack/update-istio.sh
Labels: size/XS

#394 Improve kubectl utility in e2e tests
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_suite_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/operator/operator_suite_test.go
  tests/e2e/util/certs/certs.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/L

#393 Create GH Action for update-deps
  .github/workflows/update-deps.yaml
Labels: size/M

#399 Use upstream builder image in update-deps workflow
  .github/workflows/update-deps.yaml
  tools/update_deps.sh
Labels: size/S

#403 Optimize multicluster e2e tests
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/L

#404 Faster cleanup in dualstack_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/S

#407 Documentation for dual-stack support
  docs/README.md
Labels: size/L

#412 Enable verbose logging in operator in e2e tests
  tests/e2e/util/common/e2e_utils.go
Labels: size/XS

#371 helmified imagePullSecrets and resources
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/rbac/service_account.yaml
Labels: size/XS, ok-to-test

#410 Add operatorLogLevel to Operator Helm chart
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/deployment.yaml
  chart/values.yaml
Labels: size/XS

#414 Skip control plane tests for dualStack job
  tests/e2e/controlplane/control_plane_suite_test.go
Labels: size/XS

#387 Test coverage workflow
  .github/codecov.yml
  .github/workflows/coverage.yaml
  Makefile.core.mk
Labels: size/M

#417 Add debug info to multicluster e2e tests
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
Labels: size/S

#419 Fix typo in helm-artifacts-publish ENV var command
  Makefile.core.mk
Labels: size/XS

#418 Make spec.namespace fields immutable
  api/v1alpha1/istio_types.go
  api/v1alpha1/istiorevision_types.go
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  docs/README.md
  docs/api-reference/sailoperator.io.md
  tests/integration/api/istio_test.go
Labels: size/M

#425 Minor updates to docs
  docs/README.md
Labels: size/XS

#428 Clean up gateway sections in README.md
  docs/README.md
Labels: size/XS

#432 Honor the `--log-enqueue-events` option in all controllers
  controllers/istio/istio_controller.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/webhook/webhook_controller.go
Labels: size/M

#426 Support metrics on dualStack clusters
  bundle/manifests/sail-operator-metrics-service_v1_service.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/auth_proxy_service.yaml
  chart/templates/deployment.yaml
Labels: size/XS

#433 Convert all values to pointers
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  docs/api-reference/sailoperator.io.md
  hack/api_transformer/transform.yaml
  pkg/istiovalues/digests.go
  pkg/istiovalues/digests_test.go
  pkg/istiovalues/overrides.go
  pkg/revision/reconcile_test.go
  pkg/revision/values_test.go
  tests/integration/api/istio_test.go
  tests/integration/api/istiorevision_test.go
Labels: size/XXL

#434 Remove `--default-profile` in favor of automatic platform detection
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/deployment.yaml
  cmd/main.go
  pkg/config/platform.go
Labels: size/M

#436 Reduce minimum deletion grace period to 0s
  api/v1alpha1/istio_types.go
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  bundle/manifests/sailoperator.io_remoteistios.yaml
  chart/crds/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_remoteistios.yaml
  docs/api-reference/sailoperator.io.md
  tests/integration/api/istio_test.go
Labels: size/M

#442 Improve failure messages for supportedversion unit tests
  pkg/test/util/supportedversion/supportedversion_test.go
Labels: size/S

#427 Include integration tests in code coverage calculation
  .github/workflows/coverage.yaml
  Makefile.core.mk
Labels: size/S

#443 Add spec.values.global.platform to IstioCNI
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.io_istiocnis.yaml
  chart/crds/sailoperator.io_istiocnis.yaml
  docs/api-reference/sailoperator.io.md
  hack/api_transformer/transform.yaml
Labels: size/S

#447 Add nightly-images workflow
  .github/workflows/nightly-images.yaml
Labels: size/M

#450 Pin the version of OLM we use for e2e tests
  Makefile.core.mk
  tests/e2e/common-operator-integ-suite.sh
  tools/update_deps.sh
Labels: size/S

#446 Ignore istio version suffix used in the downstream builds
  tests/e2e/util/common/e2e_utils.go
Labels: size/XS

#451 Set global.platform when not set by the user
  cmd/main.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/remoteistio/remoteistio_controller.go
  controllers/remoteistio/remoteistio_controller_test.go
  pkg/config/platform.go
  pkg/helm/values.go
  pkg/helm/values_test.go
  pkg/istiovalues/profiles.go
  pkg/revision/values.go
  pkg/revision/values_test.go
  tests/integration/api/suite_test.go
Labels: size/L

#452 Refactor logs gather flow to support multiple clusters
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_suite_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/operator/operator_suite_test.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/L

#453 Consolidate reconciler config fields into ReconcilerConfig
  cmd/main.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/remoteistio/remoteistio_controller.go
  controllers/remoteistio/remoteistio_controller_test.go
  pkg/config/config.go
  tests/integration/api/suite_test.go
Labels: size/L

#459 Refactor helm artifacts publish flow
  .github/workflows/helm.yaml
  Makefile.core.mk
  hack/helm-artifacts.sh
Labels: size/M, do-not-merge/hold

#456 Rework Multi-Primary documentation
  docs/README.md
Labels: size/L

#462 Fix log line in e2e_utils.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/XS
