Repository istio-ecosystem/sail-operator, pull requests merged in 2024-09, with the labels that each got.

#329 Fix indentation in README.md
  docs/README.md
Labels: size/XS

#328 docs: Add section for Kiali and distributed tracing OpenShift integration
  docs/README.md
Labels: size/M, ok-to-test

#332 Add release workflow
  .github/workflows/release.yaml
  hack/operatorhub/publish-bundle.sh
Labels: size/L

#334 [release-0.1] Fix OLM test setup
  tests/e2e/common-operator-integ-suite.sh
Labels: size/XS, release-notes-none

#333 [release-0.1] Add release workflow
  .github/workflows/release.yaml
  hack/operatorhub/publish-bundle.sh
Labels: size/L, release-notes-none

#340 Fix setup-multi-primary script
  docs/multicluster/setup-multi-primary.sh
Labels: size/XS

#338 Add README file for Helm charts section
  bundle/README.md
  chart/README.md
  docs/README.md
  docs/common/create-and-configure-gateways.md
  docs/common/install-bookinfo-app.md
  docs/common/install-istioctl-tool.md
  docs/common/istio-addons-integrations.md
Labels: size/XL

#327 [release-0.1] Add docs for multi-cluster install
  docs/README.md
  docs/multicluster/east-west-gateway-net1.yaml
  docs/multicluster/east-west-gateway-net2.yaml
  docs/multicluster/expose-istiod.yaml
  docs/multicluster/expose-services.yaml
  docs/multicluster/setup-multi-primary.sh
Labels: size/XXL, release-notes-none

#339 added helm overrides for proxy image as is available for operator
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/deployment.yaml
  chart/values.yaml
Labels: size/XS, ok-to-test

#350 Show name of active revision in Istio/RemoteIstio status
  api/v1alpha1/istio_types.go
  api/v1alpha1/remoteistio_types.go
  bundle/manifests/sailoperator.io_istios.yaml
  bundle/manifests/sailoperator.io_remoteistios.yaml
  chart/crds/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_remoteistios.yaml
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/remoteistio/remoteistio_controller.go
  controllers/remoteistio/remoteistio_controller_test.go
  docs/api-reference/sailoperator.io.md
Labels: size/M

#335 Add External Controlplane to user docs
  docs/README.md
  docs/multicluster/controlplane-gateway.yaml
Labels: size/XL

#352 Use Kubernetes defaults for imagePullPolicy
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/deployment.yaml
  chart/values.yaml
Labels: size/S

#357 Adding wait after olm install in olm test setup
  tests/e2e/common-operator-integ-suite.sh
Labels: size/S

#353 release workflow: Automatically adjust default release channel
  .github/workflows/release.yaml
  Makefile.core.mk
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: size/S

#359 Update test labels in the way of work documentation
  CONTRIBUTING.md
Labels: documentation

#362 Add CODE-OF-CONDUCT to the project
  CODE-OF-CONDUCT.md
Labels: size/XS

#364 Fix formatting in the charts readme page
  bundle/README.md
  chart/README.md
Labels: size/M

#366 Add pull request template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: size/M

#370 Update helm chart README
  chart/README.md
Labels: documentation, size/S

#368 E2E kubectl util refactor
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/operator/operator_suite_test.go
  tests/e2e/util/certs/certs.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/XL, test-e2e

#374 Update dependencies and fix transform
  api/v1alpha1/values_types.gen.go
  bundle/manifests/sailoperator.io_istiocnis.yaml
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  bundle/manifests/sailoperator.io_remoteistios.yaml
  chart/crds/sailoperator.io_istiocnis.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_remoteistios.yaml
  docs/api-reference/sailoperator.io.md
  go.mod
  go.sum
  hack/api_transformer/transform.yaml
Labels: size/L

#375 Add ability to specify resources in helm chart
  chart/templates/deployment.yaml
  chart/values.yaml
Labels: size/M, ok-to-test

#376 Improve pull request template
  .github/pull_request_template.md
Labels: size/M

#373 Implement e2e dualStack control plane tests
  tests/e2e/common-operator-integ-suite.sh
  tests/e2e/dualstack/dualstack_suite_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/integ-suite-kind.sh
Labels: size/L, test-e2e
