Repository istio-ecosystem/sail-operator, pull requests merged in 2024-05, with the labels that each got.

#100 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/clusterrolebinding.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#101 Allow running e2e tests against pre-deployed operator
  tests/e2e/common-operator-integ-suite.sh
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/operator/operator_install_test.go
Labels: size/M

#102 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#103 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/daemonset.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/waypoint.yaml
  resources/latest/charts/istiod/templates/deployment.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/templates/daemonset.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#109 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/files/profile-openshift-ambient.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-openshift-ambient.yaml
  resources/latest/charts/cni/templates/clusterrole.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-openshift-ambient.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/profile-openshift-ambient.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-openshift-ambient.yaml
  resources/latest/charts/ztunnel/templates/rbac.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#111 Use version 0.1.0 for community
  Makefile.core.mk
  README.md
  bundle.Dockerfile
  bundle/README.md
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  chart/Chart.yaml
Labels: size/S

#113 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#115 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/config/.hadolint.yml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#114 Adding Way of Work agreements to the read me files
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/epic_creation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CONTRIBUTING.md
  ISSUE-MANAGEMENT.md
  README.md
  SECURITY.md
  bundle/README.md
  tests/e2e/README.md
  tests/integration/README.md
Labels: enhancement, size/L

#117 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#118 Actually force-delete resources after test
  tests/e2e/util/kubectl/kubectl.go
Labels: size/XS

#119 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/networking.istio.io_virtualservices.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/crds/networking.istio.io_virtualservices.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/crds/crd-all.gen.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/injection-template.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#120 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/templates/daemonset.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#121 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.22.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#123 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  Makefile.core.mk
  bundle.Dockerfile
  bundle/manifests/networking.istio.io_workloadgroups.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  chart/crds/networking.istio.io_workloadgroups.yaml
  chart/templates/olm/scorecard.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/crds/crd-all.gen.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#122 e2e: verify the image is coming from the correct registry
  tests/e2e/README.md
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
Labels: size/S

#125 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/templates/NOTES.txt
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#131 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/_helpers.tpl
  resources/latest/charts/cni/templates/clusterrole.yaml
  resources/latest/charts/cni/templates/clusterrolebinding.yaml
  resources/latest/charts/cni/templates/configmap-cni.yaml
  resources/latest/charts/cni/templates/daemonset.yaml
  resources/latest/charts/cni/templates/network-attachment-definition.yaml
  resources/latest/charts/cni/templates/resourcequota.yaml
  resources/latest/charts/cni/templates/serviceaccount.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#132 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/configmap-cni.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/kube-gateway.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#112 Automate the bump of stable Istio releases
  hack/update-istio.sh
Labels: size/L

#133 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/configmap-cni.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#134 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#135 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#136 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#137 Create make target for helm package
  Makefile.core.mk
Labels: size/XS, ok-to-test

#140 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/templates/configmap-cni.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#143 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/waypoint.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#142 Update the README with more user focused info
  README.md
Labels: size/M, ok-to-test

#144 Move user documentation into separate file
  README.md
  docs/README.md
Labels: size/S

#146 Add gateway instructions to user docs
  docs/README.md
Labels: size/XS

#149 Remove the redundant step while creating the Istio resource.
  bundle/README.md
Labels: size/XS

#151 Fix the command to display the make targets
  README.md
Labels: size/XS

#152 Return to updating istio and client-go
  go.mod
  go.sum
  tools/update_deps.sh
Labels: size/L
