Repository istio-ecosystem/sail-operator, pull requests merged in 2024-06, with the labels that each got.

#145 Add documentation on how to integrate with Kiali
  docs/README.md
Labels: size/L

#148 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  Makefile.core.mk
  bundle/manifests/extensions.istio.io_wasmplugins.yaml
  bundle/manifests/networking.istio.io_destinationrules.yaml
  bundle/manifests/networking.istio.io_proxyconfigs.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/security.istio.io_authorizationpolicies.yaml
  bundle/manifests/security.istio.io_peerauthentications.yaml
  bundle/manifests/security.istio.io_requestauthentications.yaml
  bundle/manifests/telemetry.istio.io_telemetries.yaml
  chart/crds/extensions.istio.io_wasmplugins.yaml
  chart/crds/networking.istio.io_destinationrules.yaml
  chart/crds/networking.istio.io_proxyconfigs.yaml
  chart/crds/security.istio.io_authorizationpolicies.yaml
  chart/crds/security.istio.io_peerauthentications.yaml
  chart/crds/security.istio.io_requestauthentications.yaml
  chart/crds/telemetry.istio.io_telemetries.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/crds/crd-all.gen.yaml
  resources/latest/charts/base/files/profile-ambient.yaml
  resources/latest/charts/base/files/profile-openshift-ambient.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-ambient.yaml
  resources/latest/charts/cni/files/profile-openshift-ambient.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-ambient.yaml
  resources/latest/charts/gateway/files/profile-openshift-ambient.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/gateway-injection-template.yaml
  resources/latest/charts/istiod/files/kube-gateway.yaml
  resources/latest/charts/istiod/files/profile-ambient.yaml
  resources/latest/charts/istiod/files/profile-openshift-ambient.yaml
  resources/latest/charts/istiod/templates/deployment.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-ambient.yaml
  resources/latest/charts/ztunnel/files/profile-openshift-ambient.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#158 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/extensions.istio.io_wasmplugins.yaml
  bundle/manifests/networking.istio.io_destinationrules.yaml
  bundle/manifests/networking.istio.io_envoyfilters.yaml
  bundle/manifests/networking.istio.io_proxyconfigs.yaml
  bundle/manifests/networking.istio.io_sidecars.yaml
  bundle/manifests/networking.istio.io_virtualservices.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/security.istio.io_authorizationpolicies.yaml
  bundle/manifests/security.istio.io_peerauthentications.yaml
  bundle/manifests/security.istio.io_requestauthentications.yaml
  bundle/manifests/telemetry.istio.io_telemetries.yaml
  chart/crds/extensions.istio.io_wasmplugins.yaml
  chart/crds/networking.istio.io_destinationrules.yaml
  chart/crds/networking.istio.io_envoyfilters.yaml
  chart/crds/networking.istio.io_proxyconfigs.yaml
  chart/crds/networking.istio.io_sidecars.yaml
  chart/crds/networking.istio.io_virtualservices.yaml
  chart/crds/security.istio.io_authorizationpolicies.yaml
  chart/crds/security.istio.io_peerauthentications.yaml
  chart/crds/security.istio.io_requestauthentications.yaml
  chart/crds/telemetry.istio.io_telemetries.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/crds/crd-all.gen.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/base/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/cni/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/gateway/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/istiod/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.20.yaml
  resources/latest/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/XXL, auto-merge

#160 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/networking.istio.io_virtualservices.yaml
  bundle/manifests/operator.istio.io_istiorevisions.yaml
  bundle/manifests/operator.istio.io_istios.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/crds/networking.istio.io_virtualservices.yaml
  chart/crds/operator.istio.io_istiorevisions.yaml
  chart/crds/operator.istio.io_istios.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/crds/crd-all.gen.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/values.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/templates/serviceaccount.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/XL

#161 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/templates/daemonset.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#163 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#164 Fix e2e test failure with single version in versions.yaml
  pkg/test/util/supportedversion/supportedversion.go
  tests/integration/api/istio_test.go
Labels: size/S

#162 Add install instructions to user docs
  docs/README.md
Labels: size/S

#165 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/gateway/templates/_helpers.tpl
  resources/latest/charts/gateway/templates/deployment.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: auto-merge, size/L

#166 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#167 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/base/templates/default.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/templates/deployment.yaml
  resources/latest/charts/istiod/templates/mutatingwebhook.yaml
  resources/latest/charts/istiod/templates/revision-tags.yaml
  resources/latest/charts/istiod/templates/validatingwebhookconfiguration.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#169 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  Makefile.core.mk
  bundle.Dockerfile
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  chart/templates/olm/scorecard.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#170 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#172 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#150 Instructions for uninstalling sail-operator
  docs/README.md
Labels: size/M

#173 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#174 Include steps to create istio-cni ns when missing
  README.md
Labels: size/XS

#176 Fix minor typos in e2e readme file
  tests/e2e/README.md
Labels: size/XS

#177 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/templates/istiod-injector-configmap.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#175 Display a friendly message for missing K8s cluster
  Makefile.core.mk
Labels: size/S

#171 Add docs for sail-operator installation using CLI
  docs/README.md
Labels: size/M

#178 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#179 Modify prerequisites for installing using CLI documentation
  docs/README.md
Labels: size/XS

#180 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/templates/daemonset.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#183 Automator: Update dependencies in istio-ecosystem/sail-operator@main
  .devcontainer/devcontainer.json
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
  go.mod
  go.sum
  resources/latest/charts/base/Chart.yaml
  resources/latest/charts/cni/Chart.yaml
  resources/latest/charts/cni/values.yaml
  resources/latest/charts/gateway/Chart.yaml
  resources/latest/charts/istiod/Chart.yaml
  resources/latest/charts/istiod/values.yaml
  resources/latest/charts/ztunnel/Chart.yaml
  resources/latest/charts/ztunnel/values.yaml
  versions.yaml
Labels: size/M, auto-merge

#184 [release-0.1] Instructions for uninstalling sail-operator
  docs/README.md
Labels: size/M, release-notes-none
