Repository istio-ecosystem/sail-operator, pull requests merged in 2025-06, with the labels that each got.

#845 Add to vendors_default the possibility to add values for IstioCNI
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  pkg/istiovalues/vendor_defaults.go
  pkg/istiovalues/vendor_defaults.yaml
  pkg/istiovalues/vendor_defaults_test.go
  pkg/revision/values.go
  tests/e2e/README.md
Labels: size/XL

#868 Adding description for release workflow run
  .github/workflows/release.yaml
Labels: cherrypick/release-1.26

#877 Do not block the workflow on errors when publishing to operatorhub.io
  .github/workflows/release.yaml
Labels: size/XS, cherrypick/release-1.26

#879 [release-1.26] Do not block the workflow on errors when publishing to operatorhub.io
  .github/workflows/release.yaml
Labels: size/XS, release-notes-none

#881 Split Documentation: splitting docs, adding table of content and fixing links
  docs/README.md
  docs/addons/addons.md
  docs/addons/observability.md
  docs/common/create-and-configure-gateways.md
  docs/common/install-bookinfo-app.md
  docs/common/install-istioctl-tool.md
  docs/common/istio-addons-integrations.md
  docs/common/istio-ambient-mode.md
  docs/common/istio-ambient-waypoint.md
  docs/deployment-models/multicluster.md
  docs/deployment-models/multiple-mesh.md
  docs/deployment-models/resources/controlplane-gateway.yaml
  docs/deployment-models/resources/east-west-gateway-net1.yaml
  docs/deployment-models/resources/east-west-gateway-net2.yaml
  docs/deployment-models/resources/expose-istiod.yaml
  docs/deployment-models/resources/expose-services.yaml
  docs/deployment-models/resources/setup-multi-primary.sh
  docs/dual-stack/dual-stack.md
  docs/general/getting-started.md
  docs/general/istiod-ha.md
  docs/guidelines/example-documentation-following-guidelines.md
  docs/guidelines/guidelines.md
  docs/update-strategy/update-strategy.md
  tests/documentation_tests/README-runme.md
  tests/documentation_tests/dual-stack-runme.md
  tests/documentation_tests/example-documentation-following-guidelines-runme.md
  tests/documentation_tests/istiod-ha-runme.md
  tests/documentation_tests/multiple-mesh-runme.md
  tests/documentation_tests/update-strategy-runme.md
  tests/e2e/multicluster/multicluster_suite_test.go
Labels: size/XXL

#887 Fix "Check broken link" workflow
  .github/workflows/brokenlinks.yml
Labels: size/XS

#888 Update github action for broken links
  .github/workflows/brokenlinks.yml
Labels: size/XS

#895 [release-1.26] Enchance debug information when e2e fails: add istioctl proxy status
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/istioctl/istioctl.go
Labels: size/S, release-notes-none

#889 Improve e2e test cleanup by recording & cleaning up
  tests/e2e/README.md
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/controlplane/control_plane_update_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_externalcontrolplane_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/util/cleaner/cleaner.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/helm/helm.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/XL

#902 Consolidate multicluster operator deploy/cleanup
  tests/e2e/multicluster/multicluster_externalcontrolplane_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
Labels: size/L

#904 Annotate only our clusters when using kind
  tests/e2e/setup/setup-kind.sh
Labels: size/S

#897 (Manual cherry-pick) Add to vendors_default the possibility to add values for IstioCNI (#845)
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  pkg/istiovalues/vendor_defaults.go
  pkg/istiovalues/vendor_defaults.yaml
  pkg/istiovalues/vendor_defaults_test.go
  pkg/revision/values.go
  tests/e2e/README.md
Labels: size/XL

#910 Skip cleanup if control plane tests fail
  tests/e2e/controlplane/control_plane_suite_test.go
Labels: size/XS

#907 Adding Eventually to Helm operator install
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
  tests/e2e/operator/operator_install_test.go
Labels: size/S

#911 Fix typo in the ReportAfterSuite text
  tests/e2e/multicluster/multicluster_suite_test.go
Labels: size/XS

#915 [release-1.26] Revert: Disable imageDigest support in ztunnel controller
  controllers/ztunnel/ztunnel_controller.go
  controllers/ztunnel/ztunnel_controller_test.go
Labels: size/S, release-notes-none

#918 Fix docs for "broken_links" workflow
  .github/workflows/brokenlinks.yml
  CONTRIBUTING.md
  ISSUE-MANAGEMENT.md
  bundle/README.md
  docs/README.md
  docs/addons/addons.md
  docs/common/create-and-configure-gateways.md
  docs/deployment-models/multiple-mesh.md
  docs/dual-stack/dual-stack.md
  docs/general/getting-started.md
  docs/general/istiod-ha.md
  docs/guidelines/example-documentation-following-guidelines.md
  docs/guidelines/guidelines.md
  docs/update-strategy/update-strategy.md
  tests/documentation_tests/README-runme.md
  tests/documentation_tests/dual-stack-runme.md
  tests/documentation_tests/example-documentation-following-guidelines-runme.md
  tests/documentation_tests/istiod-ha-runme.md
  tests/documentation_tests/multiple-mesh-runme.md
  tests/documentation_tests/scripts/update-docs-examples.sh
  tests/documentation_tests/update-strategy-runme.md
  tests/e2e/README.md
Labels: size/XL

#894 Improve automated docs test run
  Makefile.core.mk
  docs/README.md
  docs/deployment-models/multiple-mesh.md
  docs/general/istiod-ha.md
  docs/guidelines/guidelines.md
  docs/update-strategy/update-strategy.md
  tests/documentation_tests/README-runme.md
  tests/documentation_tests/dual-stack-runme.md
  tests/documentation_tests/example-documentation-following-guidelines-runme.md
  tests/documentation_tests/istiod-ha-runme.md
  tests/documentation_tests/multiple-mesh-runme.md
  tests/documentation_tests/scripts/run-docs-examples.sh
  tests/documentation_tests/scripts/update-docs-examples.sh
  tests/documentation_tests/update-strategy-runme.md
Labels: size/XXL, cherrypick/release-1.26

#926 Fix docs typos
  docs/guidelines/guidelines.md
Labels: size/L

#934 [release-1.26] e2e allow to build and push setting target arch
  tests/e2e/README.md
  tests/e2e/setup/build-and-push-operator.sh
Labels: size/S, release-notes-none

#936 Stabilize e2e dual-stack test
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/controlplane/control_plane_update_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/M, ok-to-test

#922 fix IstioRevisionTag uninstall when revision namespace changes
  controllers/istiorevisiontag/istiorevisiontag_controller.go
  tests/integration/api/istiorevisiontag_test.go
Labels: size/L, cherrypick/release-1.26

#945 [release-1.26] fix IstioRevisionTag uninstall when revision namespace changes
  controllers/istiorevisiontag/istiorevisiontag_controller.go
  tests/integration/api/istiorevisiontag_test.go
Labels: size/L, release-notes-none

#931 Consolidate e2e resource creation
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/controlplane/control_plane_update_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_externalcontrolplane_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/L

#946 Cleaner improvements
  tests/e2e/util/cleaner/cleaner.go
Labels: size/S

#957 [release-1.26] Wrap a panic in Ginkgo node
  tests/e2e/controlplane/control_plane_update_test.go
  tests/integration/api/istio_test.go
Labels: size/S, release-notes-none
