Repository istio-ecosystem/sail-operator, pull requests merged in 2025-04, with the labels that each got.

#738 Add unit tests for env.go
  pkg/env/env.go
  pkg/env/env_test.go
Labels: size/L

#742 Use VERSIONS_YAML_FILE env variable only when versionsFilename is not set via ldfags
  pkg/istioversion/version.go
Labels: size/XS

#745 [release-1.0] Use VERSIONS_YAML_FILE env variable only when versionsFilename is not set via ldfags
  pkg/istioversion/version.go
Labels: size/XS, release-notes-none

#737 Add unit tests for EnqueueEventLogger
  pkg/enqueuelogger/wrapper_test.go
Labels: size/M

#740 Rename status-patch.go to status_patch.go and add unit tests
  pkg/kube/status_patch.go
  pkg/kube/status_patch_test.go
Labels: size/M

#736 Add unit tests for AdditionNotifierQueue
  go.mod
  pkg/enqueuelogger/queue_test.go
Labels: size/L

#748 Simplify AdditionNotifierQueue
  pkg/enqueuelogger/queue.go
  pkg/enqueuelogger/queue_test.go
  pkg/enqueuelogger/wrapper.go
Labels: size/M

#751 Add unit tests for predicate.IgnoreUpdate
  pkg/predicate/predicate_test.go
Labels: size/M

#752 Add unit tests for pkg/reconciler/errors.go
  pkg/reconciler/errors_test.go
Labels: size/M

#757 Add release and support strategy to README
  README.md
Labels: size/S

#760 Deprecate defaultRevision value
  api/v1/values_types.gen.go
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  docs/api-reference/sailoperator.io.md
  hack/api_transformer/transform.yaml
Labels: size/S

#756 Add unit tests for GetReferencedRevisionFromNamespace, GetReferencedRevisionFromPod, and GetInjectedRevisionFromPod
  pkg/revision/references.go
  pkg/revision/references_test.go
Labels: size/L

#758 Add unit tests for revision.ListOwned and revision.isOwnedRevision
  pkg/revision/list_test.go
Labels: size/L

#754 Bump version to 1.25
  .devcontainer/devcontainer.json
  .github/workflows/release.yaml
  .github/workflows/update-deps.yaml
  Makefile.core.mk
  api/v1/values_types.gen.go
  api/v1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/networking.istio.io_gateways.yaml
  bundle/manifests/networking.istio.io_sidecars.yaml
  bundle/manifests/networking.istio.io_virtualservices.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/sailoperator.io_istiocnis.yaml
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istiorevisiontags.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  bundle/manifests/sailoperator.io_ztunnels.yaml
  bundle/metadata/annotations.yaml
  chart/Chart.yaml
  chart/crds/networking.istio.io_gateways.yaml
  chart/crds/networking.istio.io_sidecars.yaml
  chart/crds/networking.istio.io_virtualservices.yaml
  chart/crds/sailoperator.io_istiocnis.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istiorevisiontags.yaml
  chart/crds/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
  chart/values.yaml
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/run.sh
  common/scripts/setup_env.sh
  docs/api-reference/sailoperator.io.md
  go.mod
  go.sum
Labels: size/XL

#762 Bump main to 1.26
  .github/workflows/release.yaml
  Makefile.core.mk
  bundle.Dockerfile
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  chart/Chart.yaml
  chart/values.yaml
Labels: size/S

#766 Use VERSION in release TAG
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
Labels: size/S

#768 Add olm replaces and skipRange annotations to csv
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/Chart.yaml
  chart/templates/olm/clusterserviceversion.yaml
  chart/values.yaml
Labels: size/S

#774 update golangci-overrides and run `make update-common`
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/format_go.sh
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
  tools/golangci-override.yaml
Labels: size/XL

#717 Add Openshift support for multicluster test suite
  tests/e2e/integ-suite-kind.sh
  tests/e2e/multicluster/common.go
  tests/e2e/multicluster/multicluster_externalcontrolplane_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/istioctl/istioctl.go
  tests/e2e/util/kubectl/kubectl.go
Labels: size/L

#773 Set readOnlyRootFilesystem to `true`
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/deployment.yaml
Labels: size/XS

#771 Modernize and clean up code
  controllers/istiorevision/istiorevision_controller.go
  hack/api_transformer/main.go
  pkg/converter/converter_test.go
  pkg/helm/chartmanager.go
  pkg/kube/finalizers.go
  pkg/kube/status_patch.go
  tests/e2e/util/gomega/matchers.go
  tests/e2e/util/kubectl/resourcelist_types.go
Labels: size/M

#777 Fix appVersion inconsistencies in revisiontags chart
  Makefile.core.mk
  hack/download-charts.sh
  resources/v1.21.6/charts/revisiontags/Chart.yaml
  resources/v1.22.5/charts/revisiontags/Chart.yaml
  resources/v1.22.6/charts/revisiontags/Chart.yaml
  resources/v1.22.7/charts/revisiontags/Chart.yaml
  resources/v1.22.8/charts/revisiontags/Chart.yaml
  resources/v1.23.2/charts/revisiontags/Chart.yaml
  resources/v1.23.3/charts/revisiontags/Chart.yaml
  resources/v1.23.4/charts/revisiontags/Chart.yaml
  resources/v1.23.5/charts/revisiontags/Chart.yaml
  resources/v1.24.0/charts/revisiontags/Chart.yaml
  resources/v1.24.1/charts/revisiontags/Chart.yaml
  resources/v1.24.2/charts/revisiontags/Chart.yaml
  resources/v1.24.3/charts/revisiontags/Chart.yaml
  resources/v1.24.4/charts/revisiontags/Chart.yaml
  resources/v1.25-alpha.c2ac935c/charts/revisiontags/Chart.yaml
  resources/v1.25.1/charts/revisiontags/Chart.yaml
Labels: size/M

#769 [tests] Use Job for curl-metrics in operator_install_test
  tests/e2e/operator/operator_install_test.go
Labels: size/M

#784 [release-1.0] [tests] Use Job for curl-metrics in operator_install_test
  tests/e2e/operator/operator_install_test.go
Labels: size/M, release-notes-none

#775 Fix updating pre-release istio versions
  hack/api_transformer/transform.yaml
  hack/update-istio.sh
Labels: size/XS

#792 Update GINKGO_FLAGS to allow override
  Makefile.core.mk
Labels: size/XS

#794 [release-1.0] Update GINKGO_FLAGS to allow override
  Makefile.core.mk
Labels: size/XS, release-notes-none

#797 Add unit test for istiovalues.ApplyOverrides
  pkg/istiovalues/overrides_test.go
Labels: size/M

#786 Check if IstioRevisionTag references a remote IstioRevision
  controllers/istiorevisiontag/istiorevisiontag_controller.go
  controllers/istiorevisiontag/istiorevisiontag_controller_test.go
Labels: size/M

#791 Changes in docs guidelines for docs automations
  docs/guidelines/example-documentation-following-guidelines.md
  docs/guidelines/guidelines.md
  tests/documentation_tests/example-documentation-following-guidelines-runme.md
Labels: size/S

#772 Remove omitempty from nested struct fields or replace with omitzero
  api/v1/istio_types.go
  api/v1/istiocni_types.go
  api/v1/istiorevision_types.go
  api/v1/istiorevisiontags_types.go
  api/v1alpha1/ztunnel_types.go
Labels: size/M

#801 Add label managed-by: sail-operator to all resources the operator deploys
  pkg/constants/constants.go
  pkg/helm/chartmanager.go
  pkg/helm/postrenderer.go
  pkg/helm/postrenderer_test.go
Labels: size/M

#755 Add PROFILE column
  api/v1/istio_types.go
  api/v1/istiocni_types.go
  api/v1/istiorevision_types.go
  api/v1alpha1/ztunnel_types.go
  bundle/manifests/sailoperator.io_istiocnis.yaml
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  bundle/manifests/sailoperator.io_ztunnels.yaml
  chart/crds/sailoperator.io_istiocnis.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
Labels: size/M

#727 Add ConfigMap with final Helm values to charts that don't have one
  docs/README.md
  hack/download-charts.sh
  resources/v1.21.6/charts/istiod/templates/configmap-values.yaml
  resources/v1.21.6/charts/istiod/templates/zzz_profile.yaml
  resources/v1.21.6/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.22.5/charts/istiod/templates/configmap-values.yaml
  resources/v1.22.5/charts/istiod/templates/zzz_profile.yaml
  resources/v1.22.5/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.22.6/charts/istiod/templates/configmap-values.yaml
  resources/v1.22.6/charts/istiod/templates/zzz_profile.yaml
  resources/v1.22.6/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.22.7/charts/istiod/templates/configmap-values.yaml
  resources/v1.22.7/charts/istiod/templates/zzz_profile.yaml
  resources/v1.22.7/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.22.8/charts/istiod/templates/configmap-values.yaml
  resources/v1.22.8/charts/istiod/templates/zzz_profile.yaml
  resources/v1.22.8/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.23.2/charts/istiod/templates/configmap-values.yaml
  resources/v1.23.2/charts/istiod/templates/zzz_profile.yaml
  resources/v1.23.2/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.23.3/charts/istiod/templates/configmap-values.yaml
  resources/v1.23.3/charts/istiod/templates/zzz_profile.yaml
  resources/v1.23.3/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.23.4/charts/istiod/templates/configmap-values.yaml
  resources/v1.23.4/charts/istiod/templates/zzz_profile.yaml
  resources/v1.23.4/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.23.5/charts/istiod/templates/configmap-values.yaml
  resources/v1.23.5/charts/istiod/templates/zzz_profile.yaml
  resources/v1.23.5/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.23.6/charts/istiod/templates/configmap-values.yaml
  resources/v1.23.6/charts/istiod/templates/zzz_profile.yaml
  resources/v1.23.6/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.24.0/charts/istiod/templates/configmap-values.yaml
  resources/v1.24.0/charts/istiod/templates/zzz_profile.yaml
  resources/v1.24.0/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.24.1/charts/istiod/templates/configmap-values.yaml
  resources/v1.24.1/charts/istiod/templates/zzz_profile.yaml
  resources/v1.24.1/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.24.2/charts/istiod/templates/configmap-values.yaml
  resources/v1.24.2/charts/istiod/templates/zzz_profile.yaml
  resources/v1.24.2/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.24.3/charts/istiod/templates/configmap-values.yaml
  resources/v1.24.3/charts/istiod/templates/zzz_profile.yaml
  resources/v1.24.3/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.24.4/charts/istiod/templates/configmap-values.yaml
  resources/v1.24.4/charts/istiod/templates/zzz_profile.yaml
  resources/v1.24.4/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.24.5/charts/istiod/templates/configmap-values.yaml
  resources/v1.24.5/charts/istiod/templates/zzz_profile.yaml
  resources/v1.24.5/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.25.1/charts/istiod/templates/configmap-values.yaml
  resources/v1.25.1/charts/istiod/templates/zzz_profile.yaml
  resources/v1.25.1/charts/revisiontags/templates/zzz_profile.yaml
  resources/v1.25.2/charts/istiod/templates/configmap-values.yaml
  resources/v1.25.2/charts/istiod/templates/zzz_profile.yaml
  resources/v1.25.2/charts/revisiontags/templates/zzz_profile.yaml
  tests/documentation_tests/README-runme.md
Labels: size/L
