Repository istio-ecosystem/sail-operator, pull requests merged in 2025-01, with the labels that each got.

#548 Remove duplicate newline at EOF of values_types
  api/v1alpha1/values_types.gen.go
  hack/api_transformer/main.go
Labels: size/XS

#547 Split unit/integration tests
  .github/workflows/integration-tests.yaml
  .github/workflows/unit-tests.yaml
  codecov.yml
Labels: size/S

#550 Document that env vars are strings
  docs/README.md
Labels: size/M

#546 Makefile support to deploy sample Istio with ambient profile
  Makefile.core.mk
  README.md
  chart/README.md
  chart/samples/istio-sample-kubernetes.yaml
  chart/samples/istio-sample.yaml
  chart/templates/olm/samples.yaml
  hack/update-version-list.sh
  tests/e2e/common-operator-integ-suite.sh
Labels: size/M

#552 Update version in sample yamls
  chart/samples/ambient/istio-sample.yaml
  chart/samples/ambient/istiocni-sample.yaml
  chart/samples/ambient/istioztunnel-sample.yaml
  chart/samples/istio-sample-gw-api.yaml
  chart/samples/istio-sample-revisionbased.yaml
  hack/update-version-list.sh
Labels: size/S

#555 Avoid specifying platform in the e2e tests
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_suite_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/operator/operator_suite_test.go
Labels: size/M

#559 Fix failures due to IP_FAMILIES change
  tests/e2e/integ-suite-kind.sh
Labels: size/XS

#541 e2e tests for validating Ambient deployment
  tests/e2e/ambient/ambient_suite_test.go
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/L

#560 Switch to sail-dev quay org
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/README.md
  chart/samples/gwControllerMode.yaml
  chart/values.yaml
  tests/e2e/README.md
  tests/e2e/util/common/e2e_utils.go
Labels: size/S

#562 Fix gitleaks by scanning only files
  Makefile.core.mk
Labels: size/XS

#563 Allow overriding Ambient params in IstioCNI
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.io_istiocnis.yaml
  chart/crds/sailoperator.io_istiocnis.yaml
  docs/api-reference/sailoperator.io.md
  hack/api_transformer/transform.yaml
Labels: size/M

#511 Create IstioRevisionTag documentation
  api/v1alpha1/istiorevisiontags_types.go
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/sailoperator.io_istiorevisiontags.yaml
  chart/crds/sailoperator.io_istiorevisiontags.yaml
  docs/README.md
  docs/api-reference/sailoperator.io.md
  enhancements/SEP2-revision-tags.md
Labels: size/L

#574 Remove automatic channel prefix detection
  Makefile.core.mk
Labels: size/XS

#575 [release-1.0] Remove automatic channel prefix detection
  Makefile.core.mk
Labels: size/XS, release-notes-none

#573 [release-1.0] Create IstioRevisionTag documentation
  api/v1alpha1/istiorevisiontags_types.go
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/sailoperator.io_istiorevisiontags.yaml
  chart/crds/sailoperator.io_istiorevisiontags.yaml
  docs/README.md
  docs/api-reference/sailoperator.io.md
  enhancements/SEP2-revision-tags.md
Labels: size/L, release-notes-none

#570 [release-1.0] Allow overriding Ambient params in IstioCNI
  api/v1alpha1/values_types.gen.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.io_istiocnis.yaml
  chart/crds/sailoperator.io_istiocnis.yaml
  docs/api-reference/sailoperator.io.md
  hack/api_transformer/transform.yaml
Labels: size/M, release-notes-none

#556 Remove kube-rbac-proxy
  bundle/manifests/sail-operator-metrics-service_v1_service.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/auth_proxy_service.yaml
  chart/templates/deployment.yaml
  chart/templates/rbac/auth_proxy_role_binding.yaml
  chart/templates/rbac/leader_election_role_binding.yaml
  chart/values.yaml
  cmd/main.go
  go.mod
  go.sum
  tests/e2e/operator/operator_install_test.go
  tests/e2e/operator/operator_suite_test.go
Labels: size/L

#577 [release-1.0] Remove kube-rbac-proxy
  bundle/manifests/sail-operator-metrics-service_v1_service.yaml
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/auth_proxy_service.yaml
  chart/templates/deployment.yaml
  chart/templates/rbac/auth_proxy_role_binding.yaml
  chart/templates/rbac/leader_election_role_binding.yaml
  chart/values.yaml
  cmd/main.go
  go.mod
  go.sum
  tests/e2e/operator/operator_install_test.go
  tests/e2e/operator/operator_suite_test.go
Labels: size/L, release-notes-none

#568 Fix ztunnel controller to apply values.ztunnel config
  controllers/ztunnel/ztunnel_controller.go
  pkg/istiovalues/profiles.go
  tests/e2e/ambient/ambient_test.go
Labels: size/S

#584 Use logAsJson instead of logAsJSON in ZTunnel APIs
  api/v1/values_types_extra.go
  bundle/manifests/sailoperator.io_ztunnels.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
Labels: size/S

#589 Move contributor call to Thursdays
  README.md
Labels: size/XS

#592 Fix sailoperator v1 api-docs
  Makefile.core.mk
  docs/api-reference/sailoperator.io.md
Labels: size/XXL

#594 [release-1.0] Use logAsJson instead of logAsJSON in ZTunnel APIs
  api/v1/values_types_extra.go
  bundle/manifests/sailoperator.io_ztunnels.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
Labels: size/S, release-notes-none

#582 Disable imageDigest support in ztunnel controller
  controllers/ztunnel/ztunnel_controller.go
  controllers/ztunnel/ztunnel_controller_test.go
Labels: size/S

#579 Add an Ambient mode documentation
  docs/common/images/kiali-dashboard.png
  docs/common/images/kiali-security.png
  docs/common/images/kiali-traffic-map.png
  docs/common/istio-ambient-mode.md
Labels: size/L

#598 link ambient doc in the doc/table of contents
  docs/README.md
Labels: size/XS

#596 [release-1.0] Disable imageDigest support in ztunnel controller
  controllers/ztunnel/ztunnel_controller.go
  controllers/ztunnel/ztunnel_controller_test.go
Labels: size/S, release-notes-none

#601 [release-1.0] link ambient doc in the doc/table of contents
  docs/README.md
Labels: size/XS, release-notes-none

#580 [release-1.0] Fix ztunnel controller to apply values.ztunnel config
  controllers/ztunnel/ztunnel_controller.go
  pkg/istiovalues/profiles.go
  tests/e2e/ambient/ambient_test.go
Labels: size/S, release-notes-none

#600 [release-1.0] Add an Ambient mode documentation
  docs/common/images/kiali-dashboard.png
  docs/common/images/kiali-security.png
  docs/common/images/kiali-traffic-map.png
  docs/common/istio-ambient-mode.md
Labels: size/L, release-notes-none

#595 Update ztunnel comment in api_transformer
  hack/api_transformer/transform.yaml
Labels: size/XS

#604 Helm: Remove redundant platform-specific cmd during installation
  chart/README.md
Labels: size/XS

#607 [release-1.0] Helm: Remove redundant platform-specific cmd during installation
  chart/README.md
Labels: size/XS, release-notes-none

#593 [release-1.0] Fix sailoperator v1 api-docs
  Makefile.core.mk
  docs/api-reference/sailoperator.io.md
Labels: size/XXL, release-notes-none
