Repository istio-ecosystem/sail-operator, pull requests merged in 2025-03, with the labels that each got.

#687 Fix skipping upgrade tests when only one istio version is specified
  tests/e2e/controlplane/control_plane_update_test.go
Labels: size/XS

#688 [release-1.0] Fix skipping upgrade tests when only one istio version is specified
  tests/e2e/controlplane/control_plane_update_test.go
Labels: size/XS, release-notes-none

#680 Update IstioCNI resource doc extended
  docs/README.md
Labels: documentation, size/M

#691 [release-1.0] Cleanup created clusterrolebinding after tests
  tests/e2e/operator/operator_install_test.go
Labels: size/XS, release-notes-none

#697 Add a note that version is optional in Istio CRs
  docs/README.md
  docs/common/istio-ambient-mode.md
Labels: size/S

#699 make spec.namespace field of `IstioCNI` immutable
  api/v1/istiocni_types.go
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/sailoperator.io_istiocnis.yaml
  chart/crds/sailoperator.io_istiocnis.yaml
  docs/api-reference/sailoperator.io.md
  tests/integration/api/istiocni_test.go
Labels: size/S

#694 Add a Waypoint user documentation
  docs/README.md
  docs/common/istio-ambient-mode.md
  docs/common/istio-ambient-waypoint.md
Labels: size/L

#704 Enable again automatic updates for gitleaks
  tools/update_deps.sh
Labels: size/XS

#709 Remove special CODEOWNERS for tools/ directory
  CODEOWNERS
Labels: size/XS

#713 Refactor conversion of IstioRevision conditions and add tests
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
Labels: size/L

#716 Change the OpenShift doc link to docs.redhat.com
  docs/common/istio-ambient-mode.md
Labels: size/XS

#721 Add NAMESPACE column to Sail resource kinds
  api/v1/istio_types.go
  api/v1/istiocni_types.go
  api/v1/istiorevision_types.go
  api/v1alpha1/ztunnel_types.go
  bundle/manifests/sailoperator.io_istiocnis.yaml
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  bundle/manifests/sailoperator.io_ztunnels.yaml
  chart/crds/sailoperator.io_istiocnis.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
Labels: size/M

#722 Remove TYPE column from IstioRevision
  api/v1/istiorevision_types.go
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
Labels: size/XS

#711 Check IstioCNI status for IstioRevisions that depend on IstioCNI
  api/v1/istio_types.go
  api/v1/istiorevision_types.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  docs/api-reference/sailoperator.io.md
  pkg/revision/dependency.go
  pkg/revision/dependency_test.go
  tests/integration/api/istiorevision_test.go
Labels: size/XL

#726 Enable IstioCNI for dualStack e2e tests
  tests/e2e/dualstack/dualstack_test.go
Labels: size/XS

#733 Update kiali example
  docs/README.md
Labels: size/S

#741 Fix setup-multi-primary.sh script
  docs/multicluster/setup-multi-primary.sh
Labels: size/S

#739 Add unit tests for key.go
  pkg/kube/key_test.go
Labels: size/M
