Repository istio-ecosystem/sail-operator, pull requests merged in 2025-08, with the labels that each got.

#1081 [release-1.26] Getting more releases from github
  hack/update-istio.sh
Labels: size/XS, release-notes-none

#1083 [release-1.26] Don't do digest pinning by default
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
Labels: size/L

#1097 Updating release process doc
  RELEASE-PROCESS.md
Labels: size/S

#1090 Get istioctl binaries from container image
  Makefile.core.mk
  tools/get-istioctl.sh
Labels: size/L

#1080 Adding specific docs for macOS developers
  README.md
  docs/macos/develop-on-macos.md
Labels: size/M

#1085 [release-1.26] Reconcile only pods in IstioRevision controller (#1025)
  controllers/istiorevision/istiorevision_controller.go
  tests/integration/api/istiorevision_test.go
Labels: size/L

#1112 [release-1.26] Increase mem limit of sail operator. (#1104)
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
Labels: size/XS

#1108 fix: prevent vendor defaults get overridden from user values
  pkg/istiovalues/vendor_defaults.go
  pkg/istiovalues/vendor_defaults_test.go
Labels: size/M, ok-to-test

#1107 Adding support for configuring the max concurrent reconciles
  cmd/main.go
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/istiorevisiontag/istiorevisiontag_controller.go
  controllers/istiorevisiontag/istiorevisiontag_controller_test.go
  controllers/webhook/webhook_controller.go
  controllers/webhook/webhook_controller_test.go
  pkg/config/config.go
  tests/integration/api/suite_test.go
Labels: size/M

#1144 Fix doc test errors
  docs/guidelines/example-documentation-following-guidelines.md
Labels: size/S, cherrypick/release-1.27

#1141 docs: remove "$" prefix from shell code blocks in all markdown files
  bundle/README.md
  chart/README.md
  docs/addons/addons.md
  docs/common/create-and-configure-gateways.md
  docs/common/istio-ambient-mode.md
  docs/deployment-models/multiple-mesh.md
  docs/general/plugin-ca.md
  tests/e2e/README.md
Labels: size/L

#1145 [release-1.26] check global hub/tag before setting image digests from configuration
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/ztunnel/ztunnel_controller.go
  controllers/ztunnel/ztunnel_controller_test.go
  pkg/istiovalues/digests.go
  pkg/istiovalues/digests_test.go
Labels: size/L, release-notes-none

#1161 [release-1.27] check global hub/tag before setting image digests from configuration
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/ztunnel/ztunnel_controller.go
  controllers/ztunnel/ztunnel_controller_test.go
  pkg/istiovalues/digests.go
  pkg/istiovalues/digests_test.go
Labels: size/L, release-notes-none

#1167 Revert default MaxConcurrentReconciles to 1
  cmd/main.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/istiorevisiontag/istiorevisiontag_controller_test.go
  controllers/webhook/webhook_controller_test.go
Labels: size/S, cherrypick/release-1.26, cherrypick/release-1.27

#1155 Update Helm documentation
  README.md
  chart/README.md
Labels: size/L

#1169 [release-1.26] Revert default MaxConcurrentReconciles to 1
  cmd/main.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/istiorevisiontag/istiorevisiontag_controller_test.go
  controllers/webhook/webhook_controller_test.go
Labels: size/S, release-notes-none

#1170 [release-1.26] Fixing istiorevision int test for PDB
  tests/integration/api/istiorevision_test.go
Labels: size/XS

#1157 docs: remove remaining "$" prefixes from code blocks
  chart/README.md
  docs/README.md
  docs/addons/observability.md
  docs/common/create-and-configure-gateways.md
  docs/common/install-istioctl-tool.md
  docs/common/istio-addons-integrations.md
  docs/deployment-models/multiple-mesh.md
  docs/dual-stack/dual-stack.md
  docs/general/getting-started.md
  docs/update-strategy/update-strategy.md
Labels: size/L

#1175 [release-1.0][backport] Adding labels to test and updating the documentation (#817)
  tests/e2e/README.md
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/controlplane/control_plane_update_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
  tests/e2e/operator/operator_install_test.go
Labels: size/M
