Repository istio-ecosystem/sail-operator, pull requests merged in 2025-07, with the labels that each got.

#958 [release-1.26] Sync istio modules with the latest used istio version
  api/v1/values_types.gen.go
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  bundle/manifests/sailoperator.io_ztunnels.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
  docs/api-reference/sailoperator.io.md
  go.mod
  go.sum
Labels: size/M

#961 [release-1.0] FBC changes
  .github/workflows/nightly-images.yaml
  .github/workflows/release.yaml
  Makefile.core.mk
  hack/operatorhub/publish-bundle.sh
Labels: size/L, tide/merge-method-merge

#962 Fix previous version for 1.26.2
  Makefile.core.mk
Labels: size/XS

#968 Fix Panic when creating ztunnel CR
  controllers/ztunnel/ztunnel_controller.go
Labels: size/XS

#949 Container: only use required packages
  Dockerfile
Labels: ok-to-test, size/S

#974 [release-1.26] Skip succeeded
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/istiorevisiontag/istiorevisiontag_controller.go
Labels: size/S, release-notes-none

#977 [release-1.26] Annotate only our clusters when using kind
  tests/e2e/setup/setup-kind.sh
Labels: size/S, release-notes-none

#978 [release-1.26] Skip cleanup if control plane tests fail
  tests/e2e/controlplane/control_plane_suite_test.go
Labels: size/XS, release-notes-none

#981 [release-1.26] Update VERSIONS_YAML_FILE e2e test information
  README.md
  tests/e2e/README.md
Labels: size/XS, release-notes-none

#982 [release-1.26] Cleaner improvements
  tests/e2e/util/cleaner/cleaner.go
Labels: size/S, release-notes-none

#979 [release-1.26] Adding Eventually to Helm operator install
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
  tests/e2e/operator/operator_install_test.go
Labels: size/S, release-notes-none

#988 Manual Cherry Picks for 1.26
  tests/e2e/ambient/ambient_suite_test.go
  tests/e2e/ambient/ambient_test.go
  tests/e2e/common-operator-integ-suite.sh
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/dualstack/dualstack_suite_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/integ-suite-kind.sh
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/multicontrolplane/multi_control_plane_suite_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/operator/operator_suite_test.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/helm/helm.go
Labels: size/L

#971 Try to uninstall releases in `uninstalling` status
  pkg/helm/chartmanager.go
  pkg/helm/chartmanager_test.go
Labels: size/S

#994 [release-1.26] Add base chart support (#802)
  Makefile.core.mk
  api/v1/istiorevision_types.go
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/templates/rbac/role.yaml
  cmd/main.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevisiontag/istiorevisiontag_controller.go
  controllers/ztunnel/ztunnel_controller.go
  hack/download-charts.sh
  hack/lint-watches.sh
  pkg/config/config.go
  pkg/constants/constants.go
  pkg/helm/chartmanager.go
  pkg/helm/chartmanager_test.go
  pkg/helm/postrenderer.go
  pkg/helm/postrenderer_test.go
  resources/v1.24.0/charts/base/files/crd-all.gen.yaml
  resources/v1.24.0/charts/base/templates/crds.yaml
  resources/v1.24.1/charts/base/files/crd-all.gen.yaml
  resources/v1.24.1/charts/base/templates/crds.yaml
  resources/v1.24.2/charts/base/files/crd-all.gen.yaml
  resources/v1.24.2/charts/base/templates/crds.yaml
  resources/v1.24.3/charts/base/files/crd-all.gen.yaml
  resources/v1.24.3/charts/base/templates/crds.yaml
  resources/v1.24.4/charts/base/files/crd-all.gen.yaml
  resources/v1.24.4/charts/base/templates/crds.yaml
  resources/v1.24.5/charts/base/files/crd-all.gen.yaml
  resources/v1.24.5/charts/base/templates/crds.yaml
  resources/v1.24.6/charts/base/files/crd-all.gen.yaml
  resources/v1.24.6/charts/base/templates/crds.yaml
  resources/v1.25.1/charts/base/files/crd-all.gen.yaml
  resources/v1.25.1/charts/base/templates/crds.yaml
  resources/v1.25.2/charts/base/files/crd-all.gen.yaml
  resources/v1.25.2/charts/base/templates/crds.yaml
  resources/v1.25.3/charts/base/files/crd-all.gen.yaml
  resources/v1.25.3/charts/base/templates/crds.yaml
  resources/v1.26.0/charts/base/files/crd-all.gen.yaml
  resources/v1.26.0/charts/base/templates/crds.yaml
  resources/v1.26.1/charts/base/files/crd-all.gen.yaml
  resources/v1.26.1/charts/base/templates/crds.yaml
  resources/v1.26.2/charts/base/files/crd-all.gen.yaml
  resources/v1.26.2/charts/base/templates/crds.yaml
  tests/integration/api/istiobase_test.go
  tests/integration/api/istiorevisiontag_test.go
  tests/integration/api/suite_test.go
Labels: size/XL

#999 adding tolerations
  chart/templates/deployment.yaml
Labels: size/XS, ok-to-test

#1002 refactors IstioRevision integration tests
  tests/integration/api/istio_test.go
  tests/integration/api/istiorevision_test.go
Labels: ok-to-test, size/XL

#1007 [release-1.0] Format the CSV using yq to easily process it later via yq if needed
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
Labels: size/XXL

#1008 [release-1.26] Format the CSV using yq to easily process it later via yq if needed
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
Labels: size/XXL

#1010 Update istiod HA documentation
  docs/general/istiod-ha.md
Labels: size/S

#1017 API transformer: map MeshConfigServiceScopeConfigs fields
  hack/api_transformer/transform.yaml
Labels: bug, size/XS

#1015 Bump helm.sh/helm/v3 to v3.18.4
  go.mod
  go.sum
  licenses/github.com/distribution/reference/LICENSE
  licenses/github.com/docker/cli/LICENSE
  licenses/github.com/docker/distribution/LICENSE
  licenses/github.com/docker/docker-credential-helpers/LICENSE
  licenses/github.com/docker/docker/LICENSE
  licenses/github.com/docker/docker/contrib/busybox/LICENSE
  licenses/github.com/docker/go-connections/LICENSE
  licenses/github.com/docker/go-metrics/LICENSE
  licenses/github.com/gorilla/mux/LICENSE
  licenses/github.com/moby/locker/LICENSE
  licenses/oras.land/oras-go/v2/LICENSE
Labels: size/XXL

#1026 [release-1.26] Bump helm.sh/helm/v3 to v3.18.4
  go.mod
  go.sum
  licenses/github.com/distribution/reference/LICENSE
  licenses/github.com/docker/cli/LICENSE
  licenses/github.com/docker/distribution/LICENSE
  licenses/github.com/docker/docker-credential-helpers/LICENSE
  licenses/github.com/docker/docker/LICENSE
  licenses/github.com/docker/docker/contrib/busybox/LICENSE
  licenses/github.com/docker/go-connections/LICENSE
  licenses/github.com/docker/go-metrics/LICENSE
  licenses/github.com/gorilla/mux/LICENSE
  licenses/github.com/moby/locker/LICENSE
  licenses/oras.land/oras-go/v2/LICENSE
Labels: size/XXL

#1025 Reconcile only pods in IstioRevision controller
  controllers/istiorevision/istiorevision_controller.go
  tests/integration/api/istiorevision_test.go
Labels: size/L

#1032 [release-1.25] Bump helm.sh/helm/v3 to v3.17.4
  go.mod
  go.sum
Labels: size/XS

#1033 [release-1.0] Bump helm.sh/helm/v3 to v3.17.4
  go.mod
  go.sum
Labels: size/M

#1036 Adding link to badge in README
  README.md
Labels: size/XS

#1040 [release-1.26] Try to uninstall releases in `uninstalling` status
  pkg/helm/chartmanager.go
  pkg/helm/chartmanager_test.go
Labels: size/S, release-notes-none

#995 Fix misleading getting-started.md regarding meshConfig
  docs/general/getting-started.md
Labels: size/XS, ok-to-test

#1047 [release-1.26] cherry-pick of "add postrender logic to not set validating webhook failurePolicy (#1042)"
  pkg/helm/chartmanager.go
  pkg/helm/postrenderer.go
  pkg/helm/postrenderer_test.go
  tests/integration/api/istiobase_test.go
  tests/integration/api/istiorevision_test.go
Labels: size/L

#1050 [release-1.26] api_transformer: support go.mod replace directives
  hack/api_transformer/main.go
Labels: size/S, release-notes-none

#1051 Add new CNIConfig values rewrite
  hack/api_transformer/transform.yaml
Labels: size/XS

#1056 [release-1.26] adding tolerations
  chart/templates/deployment.yaml
Labels: size/XS, release-notes-none

#1063 Print configuration_converter.sh std output
  pkg/converter/converter_test.go
Labels: size/XS

#1066 Modify MultiControlPlane Test to run for all supported versions (#972)
  tests/e2e/multicontrolplane/multi_control_plane_suite_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
Labels: size/L

#1072 [release-1.26] Make sure the Istio charts are always pulled first
  Makefile.core.mk
Labels: size/XS, release-notes-none

#1074 Fix values.pilot.envVarFrom field type
  api/v1/values_types.gen.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  docs/api-reference/sailoperator.io.md
  hack/api_transformer/transform.yaml
Labels: size/XL

#1075 Getting more releases from github
  hack/update-istio.sh
Labels: size/XS

#1077 [release-1.26] Fix values.pilot.envVarFrom field type
  api/v1/values_types.gen.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  docs/api-reference/sailoperator.io.md
  hack/api_transformer/transform.yaml
Labels: size/XL, release-notes-none
