Repository istio-ecosystem/sail-operator, pull requests merged in 2025-02, with the labels that each got.

#613 Use gcr.io for Istio images and quay.io/sail-dev for sample applications
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  hack/download-charts.sh
  resources/v1.21.6/charts/cni/values.yaml
  resources/v1.21.6/charts/istiod/values.yaml
  resources/v1.21.6/charts/revisiontags/values.yaml
  resources/v1.21.6/charts/ztunnel/values.yaml
  resources/v1.22.5/charts/cni/values.yaml
  resources/v1.22.5/charts/istiod/values.yaml
  resources/v1.22.5/charts/revisiontags/values.yaml
  resources/v1.22.5/charts/ztunnel/values.yaml
  resources/v1.22.6/charts/cni/values.yaml
  resources/v1.22.6/charts/istiod/values.yaml
  resources/v1.22.6/charts/revisiontags/values.yaml
  resources/v1.22.6/charts/ztunnel/values.yaml
  resources/v1.22.7/charts/cni/values.yaml
  resources/v1.22.7/charts/istiod/values.yaml
  resources/v1.22.7/charts/revisiontags/values.yaml
  resources/v1.22.7/charts/ztunnel/values.yaml
  resources/v1.22.8/charts/cni/values.yaml
  resources/v1.22.8/charts/istiod/values.yaml
  resources/v1.22.8/charts/revisiontags/values.yaml
  resources/v1.22.8/charts/ztunnel/values.yaml
  resources/v1.23.2/charts/cni/values.yaml
  resources/v1.23.2/charts/istiod-remote/values.yaml
  resources/v1.23.2/charts/istiod/values.yaml
  resources/v1.23.2/charts/revisiontags/values.yaml
  resources/v1.23.2/charts/ztunnel/values.yaml
  resources/v1.23.3/charts/cni/values.yaml
  resources/v1.23.3/charts/istiod-remote/values.yaml
  resources/v1.23.3/charts/istiod/values.yaml
  resources/v1.23.3/charts/revisiontags/values.yaml
  resources/v1.23.3/charts/ztunnel/values.yaml
  resources/v1.23.4/charts/cni/values.yaml
  resources/v1.23.4/charts/istiod-remote/values.yaml
  resources/v1.23.4/charts/istiod/values.yaml
  resources/v1.23.4/charts/revisiontags/values.yaml
  resources/v1.23.4/charts/ztunnel/values.yaml
  resources/v1.24.0/charts/cni/values.yaml
  resources/v1.24.0/charts/istiod/values.yaml
  resources/v1.24.0/charts/revisiontags/values.yaml
  resources/v1.24.0/charts/ztunnel/values.yaml
  resources/v1.24.1/charts/cni/values.yaml
  resources/v1.24.1/charts/istiod/values.yaml
  resources/v1.24.1/charts/revisiontags/values.yaml
  resources/v1.24.1/charts/ztunnel/values.yaml
  resources/v1.24.2/charts/cni/values.yaml
  resources/v1.24.2/charts/istiod/values.yaml
  resources/v1.24.2/charts/revisiontags/values.yaml
  resources/v1.24.2/charts/ztunnel/values.yaml
  samples/helloworld/helloworld.yaml
  samples/httpbin/httpbin.yaml
  samples/sleep/sleep.yaml
  samples/tcp-echo/tcp-echo-dual-stack.yaml
  samples/tcp-echo/tcp-echo-ipv4.yaml
  samples/tcp-echo/tcp-echo-ipv6.yaml
  tests/e2e/util/common/e2e_utils.go
Labels: size/XL, cherrypick/release-1.0

#615 [release-1.0] Use gcr.io for Istio images and quay.io/sail-dev for sample applications (#613)
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  hack/download-charts.sh
  resources/v1.23.0/charts/cni/values.yaml
  resources/v1.23.0/charts/istiod-remote/values.yaml
  resources/v1.23.0/charts/istiod/values.yaml
  resources/v1.23.0/charts/revisiontags/values.yaml
  resources/v1.23.0/charts/ztunnel/values.yaml
  resources/v1.23.3/charts/cni/values.yaml
  resources/v1.23.3/charts/istiod-remote/values.yaml
  resources/v1.23.3/charts/istiod/values.yaml
  resources/v1.23.3/charts/revisiontags/values.yaml
  resources/v1.23.3/charts/ztunnel/values.yaml
  resources/v1.23.4/charts/cni/values.yaml
  resources/v1.23.4/charts/istiod-remote/values.yaml
  resources/v1.23.4/charts/istiod/values.yaml
  resources/v1.23.4/charts/revisiontags/values.yaml
  resources/v1.23.4/charts/ztunnel/values.yaml
  resources/v1.24.1/charts/cni/values.yaml
  resources/v1.24.1/charts/istiod/values.yaml
  resources/v1.24.1/charts/revisiontags/values.yaml
  resources/v1.24.1/charts/ztunnel/values.yaml
  resources/v1.24.2/charts/cni/values.yaml
  resources/v1.24.2/charts/istiod/values.yaml
  resources/v1.24.2/charts/revisiontags/values.yaml
  resources/v1.24.2/charts/ztunnel/values.yaml
  samples/helloworld/helloworld.yaml
  samples/httpbin/httpbin.yaml
  samples/sleep/sleep.yaml
  samples/tcp-echo/tcp-echo-dual-stack.yaml
  samples/tcp-echo/tcp-echo-ipv4.yaml
  samples/tcp-echo/tcp-echo-ipv6.yaml
  tests/e2e/util/common/e2e_utils.go
Labels: size/XL

#591 Add an e2e test for Ambient config in IstioCNI
  tests/e2e/ambient/ambient_test.go
Labels: size/S

#611 Add workflow to detect broken links in doc
  .github/ISSUE_TEMPLATE/broken-link.md
  .github/workflows/brokenlinks.yml
  .mdlinkcheck.json
Labels: size/M

#617 [release-1.0] Add an e2e test for Ambient config in IstioCNI
  tests/e2e/ambient/ambient_test.go
Labels: auto-merge, size/S, release-notes-none

#621 [Doc] Updates to dual-stack section
  docs/README.md
Labels: size/S

#622 [release-1.0] [Doc] Updates to dual-stack section
  docs/README.md
Labels: size/S, release-notes-none

#618 Capture ztunnel details on e2e failures
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/M

#625 Add documentation for version alias
  docs/README.md
Labels: needs-ok-to-test, size/XS, ok-to-test

#630 [docs] Add PodMonitor note for Prometheus in Ambient docs
  docs/common/istio-ambient-mode.md
Labels: needs-ok-to-test, size/XS, ok-to-test

#634 Delete IstioCNI namespace in dualStack e2e tests
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_test.go
Labels: size/S

#636 Allow setting vendor-specific defaults
  README.md
  pkg/istiovalues/vendor_defaults.go
  pkg/istiovalues/vendor_defaults.yaml
  pkg/istiovalues/vendor_defaults_test.go
  pkg/revision/values.go
Labels: size/L

#637 [release-1.0] Allow setting vendor-specific defaults
  README.md
  pkg/istiovalues/vendor_defaults.go
  pkg/istiovalues/vendor_defaults.yaml
  pkg/istiovalues/vendor_defaults_test.go
  pkg/revision/values.go
Labels: size/L, release-notes-none

#619 Set Istiod env COMPLIANCE_POLICY when running on a FIPS enabled OpenShift cluster
  pkg/istiovalues/fips.go
  pkg/istiovalues/fips_test.go
  pkg/revision/values.go
  pkg/revision/values_test.go
Labels: size/L

#641 Increate timeout for e2e test execution
  tests/e2e/common-operator-integ-suite.sh
Labels: size/XS, test-e2e

#640 Add missing link for: Example using the RevisionBased strategy and and IstioRevisionTag
  docs/README.md
Labels: documentation, size/XS

#642 [release-1.0] Increate timeout for e2e test execution
  tests/e2e/common-operator-integ-suite.sh
Labels: size/XS, release-notes-none

#631 Document branching/release process
  README.md
  RELEASE-PROCESS.md
Labels: size/M

#644 [release-1.0] Set Istiod env COMPLIANCE_POLICY when running on a FIPS enabled OpenShift cluster
  pkg/istiovalues/fips.go
  pkg/istiovalues/fips_test.go
  pkg/revision/values.go
  pkg/revision/values_test.go
Labels: size/L, release-notes-none

#648 Fix validation in the ambient doc
  docs/common/istio-ambient-mode.md
Labels: size/XS

#649 [release-1.0] Fix validation in the ambient doc
  docs/common/istio-ambient-mode.md
Labels: size/XS, release-notes-none

#650 Add supported archs to CSV
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/olm/clusterserviceversion.yaml
  chart/values.yaml
Labels: size/S

#652 [release-1.0] Add supported archs to CSV
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/olm/clusterserviceversion.yaml
  chart/values.yaml
Labels: size/S

#632 Variabilize static linking ldflags for FIPS compliance
  Makefile.core.mk
Labels: size/S, cherrypick/release-1.0

#654 Disables pruning for istios that potentially manage external revs
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
Labels: size/M

#657 [release-1.0] Disables pruning for istios that potentially manage external revs
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
Labels: size/M, release-notes-none

#660 Rollback gitleaks version until issue with 1.24 is fixed
  Makefile.core.mk
  tools/update_deps.sh
Labels: size/XS

#662 [release-1.0] Add version alias support (#566)
  Makefile.core.mk
  api/v1/istio_types.go
  api/v1/istiocni_types.go
  api/v1alpha1/ztunnel_types.go
  bundle/README.md
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/manifests/sailoperator.io_istiocnis.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  bundle/manifests/sailoperator.io_ztunnels.yaml
  chart/crds/sailoperator.io_istiocnis.yaml
  chart/crds/sailoperator.io_istios.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
  chart/values.yaml
  controllers/istio/istio_controller.go
  controllers/istio/istio_controller_test.go
  controllers/istiocni/istiocni_controller.go
  controllers/istiocni/istiocni_controller_test.go
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/ztunnel/ztunnel_controller.go
  controllers/ztunnel/ztunnel_controller_test.go
  docs/api-reference/sailoperator.io.md
  hack/patch-csv.sh
  hack/remove-old-versions.sh
  hack/update-istio.sh
  hack/update-version-list.sh
  pkg/istioversion/version.go
  pkg/istioversion/version_test.go
  pkg/istioversion/versions.yaml
  pkg/test/util/supportedversion/supportedversion.go
  pkg/test/util/supportedversion/supportedversion_test.go
  tests/e2e/ambient/ambient_test.go
  tests/e2e/common-operator-integ-suite.sh
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/util/common/e2e_utils.go
  tests/integration/api/istio_test.go
  tests/integration/api/istiocni_test.go
  tests/integration/api/istiorevision_test.go
  tests/integration/api/istiorevisiontag_test.go
  versions.yaml
Labels: size/XXL

#643 [release-1.0] Add missing link for: Example using the RevisionBased strategy and and IstioRevisionTag
  docs/README.md
Labels: size/XS, release-notes-none

#623 Add contributor meeting information to the contributor.md file
  CONTRIBUTING.md
Labels: documentation, size/XS

#663 Make environment variable consistent
  tests/e2e/common-operator-integ-suite.sh
Labels: size/XS, ok-to-test

#667 Ensure e2e tests use the correct versions yaml file
  pkg/env/env.go
  pkg/istioversion/version.go
  tests/e2e/ambient/ambient_suite_test.go
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/dualstack/dualstack_suite_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/multicontrolplane/multi_control_plane_suite_test.go
  tests/e2e/operator/operator_suite_test.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/istioctl/istioctl.go
Labels: size/S, cherrypick/release-1.0

#669 [release-1.0] Ensure e2e tests use the correct versions yaml file (#667)
  pkg/env/env.go
  pkg/istioversion/version.go
  tests/e2e/ambient/ambient_suite_test.go
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/dualstack/dualstack_suite_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/operator/operator_suite_test.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/istioctl/istioctl.go
Labels: size/S

#664 [release-1.0] Make environment variable consistent
  tests/e2e/common-operator-integ-suite.sh
Labels: size/XS, release-notes-none

#677 Fix sample yaml in readme file
  README.md
Labels: size/S

#656 e2e revisiontag
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/controlplane/control_plane_update_test.go
Labels: size/L, test-e2e, cherrypick/release-1.0

#683 [Manual Cherry-pick to release-1.0 branch] e2e IstioRevisionTag test
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/controlplane/control_plane_update_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/XL

#676 External controlplane e2e test
  docs/README.md
  tests/e2e/multicluster/common.go
  tests/e2e/multicluster/multicluster_externalcontrolplane_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/util/common/e2e_utils.go
  tests/e2e/util/istioctl/istioctl.go
Labels: size/XL, test-e2e, cherrypick/release-1.0
