Repository istio-ecosystem/sail-operator, pull requests merged in 2025-09, with the labels that each got.

#1184 [release-1.0] bump versions after downstream 3.0.4
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/Chart.yaml
  chart/values.yaml
Labels: size/S

#1186 adding accessLogFile parameter to istiod config
  pkg/converter/converter_test.go
  tools/configuration-converter.sh
Labels: size/S

#1189 move common functions under util/common
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/util/common/e2e_utils.go
Labels: size/M

#1193 Fix api_transformer's handling of inline comments
  hack/api_transformer/main.go
Labels: size/XS, cherrypick/release-1.25, cherrypick/release-1.26, cherrypick/release-1.27

#1195 [release-1.27] Fix api_transformer's handling of inline comments
  hack/api_transformer/main.go
Labels: size/XS, release-notes-none

#989 Deterministic solution for name clashes
  api/v1/istiorevision_types.go
  api/v1/istiorevisiontags_types.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevisiontag/istiorevisiontag_controller.go
  docs/api-reference/sailoperator.io.md
  pkg/reconciler/errors.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
  tests/integration/api/istiorevision_test.go
  tests/integration/api/istiorevisiontag_test.go
Labels: size/L, cherrypick/release-1.26

#1197 [release-1.26] Deterministic solution for name clashes
  api/v1/istiorevision_types.go
  api/v1/istiorevisiontags_types.go
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevisiontag/istiorevisiontag_controller.go
  docs/api-reference/sailoperator.io.md
  pkg/reconciler/errors.go
  pkg/validation/validation.go
  pkg/validation/validation_test.go
  tests/integration/api/istiorevision_test.go
  tests/integration/api/istiorevisiontag_test.go
Labels: size/L, release-notes-none

#1188 Add commit validation GH action
  .commit-check.yml
  .github/workflows/commit-validation.yaml
  CONTRIBUTING.md
Labels: size/M

#1219 [release-1.26] Fix junit report generation
  tests/e2e/common-operator-integ-suite.sh
Labels: size/S, release-notes-none

#1221 [release-1.27] Fix junit report generation
  tests/e2e/common-operator-integ-suite.sh
Labels: size/S, release-notes-none

#1222 Make sure there are no empty channels after cleaning nightly builds
  hack/operatorhub/clean-nightlies.sh
Labels: size/XS

#1206 Document steps for single network multicluster
  docs/README.md
  docs/deployment-models/multicluster.md
Labels: size/L, cherrypick/release-1.27

#1224 [release-1.0] Bump to 1.0.6 version
  Makefile.core.mk
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/Chart.yaml
  chart/values.yaml
Labels: size/S

#1227 fix(e2e): Add cleanup trap to prevent false positives in CI test runs
  tests/e2e/common-operator-integ-suite.sh
Labels: size/M

#1233 Fix new lint errors
  controllers/istio/istio_controller.go
  tests/e2e/util/cleaner/cleaner.go
Labels: size/XS

#1235 [release-1.27] Fix new lint errors
  controllers/istio/istio_controller.go
  tests/e2e/util/cleaner/cleaner.go
Labels: size/XS, release-notes-none

#1236 fix: remove MeshConfig from ZTunnel CRD
  api/v1/values_types_extra.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.io_ztunnels.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
  docs/api-reference/sailoperator.io.md
Labels: size/XXL, cherrypick/release-1.27

#1238 Adding check_cluster_operators for OCP clusters
  tests/e2e/common-operator-integ-suite.sh
Labels: size/M

#1243 Adding check_cluster_operators for OCP clusters (#1238)
  tests/e2e/common-operator-integ-suite.sh
Labels: size/M

#1244 Adding check_cluster_operators for OCP clusters (#1238)
  tests/e2e/common-operator-integ-suite.sh
Labels: size/M

#1245 Fix compability update-deps script
  tools/update_deps.sh
Labels: size/M
