Repository istio-ecosystem/sail-operator, pull requests merged in 2025-05, with the labels that each got.

#806 Fix issue 805: update ZTunnel resource logLevel in values
  api/v1/values_types_extra.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.io_ztunnels.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
  docs/api-reference/sailoperator.io.md
Labels: size/M

#705 Add `make cluster` command
  Makefile.core.mk
  README.md
  tests/e2e/setup/setup-kind.sh
Labels: size/M, ok-to-test

#764 Add missing ztunnel config params in ztunnel crd
  api/v1/values_types_extra.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/sailoperator.io_ztunnels.yaml
  chart/crds/sailoperator.io_ztunnels.yaml
  docs/api-reference/sailoperator.io.md
Labels: size/M

#804 Adding new examples to docs automation
  docs/README.md
  docs/guidelines/guidelines.md
  tests/documentation_tests/README-runme.md
  tests/documentation_tests/scripts/prebuilt-func.sh
  tests/documentation_tests/scripts/run-docs-examples.sh
Labels: size/XXL

#815 fix generation of version list
  hack/update-version-list.sh
Labels: size/XS

#817 Adding labels to test and updating the documentation
  tests/e2e/README.md
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/controlplane/control_plane_update_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/multicluster/multicluster_externalcontrolplane_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
  tests/e2e/operator/operator_install_test.go
Labels: size/M

#823 Do not ignore failures when downloading charts
  Makefile.core.mk
Labels: size/XS

#824 [release-1.0] Do not ignore failures when downloading charts
  Makefile.core.mk
Labels: size/XS

#829 Bump main to 1.27
  .github/workflows/release.yaml
  Makefile.core.mk
  bundle.Dockerfile
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  chart/Chart.yaml
  chart/values.yaml
Labels: size/S

#834 [release-1.26] Updating common + dependencies, using 1.26.0 istio go …
  .devcontainer/devcontainer.json
  .github/workflows/update-deps.yaml
  Makefile.core.mk
  api/v1/values_types.gen.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/extensions.istio.io_wasmplugins.yaml
  bundle/manifests/networking.istio.io_destinationrules.yaml
  bundle/manifests/networking.istio.io_gateways.yaml
  bundle/manifests/networking.istio.io_serviceentries.yaml
  bundle/manifests/networking.istio.io_sidecars.yaml
  bundle/manifests/networking.istio.io_virtualservices.yaml
  bundle/manifests/networking.istio.io_workloadentries.yaml
  bundle/manifests/networking.istio.io_workloadgroups.yaml
  bundle/manifests/sailoperator.io_istiorevisions.yaml
  bundle/manifests/sailoperator.io_istios.yaml
  chart/crds/extensions.istio.io_wasmplugins.yaml
  chart/crds/networking.istio.io_destinationrules.yaml
  chart/crds/networking.istio.io_gateways.yaml
  chart/crds/networking.istio.io_serviceentries.yaml
  chart/crds/networking.istio.io_sidecars.yaml
  chart/crds/networking.istio.io_virtualservices.yaml
  chart/crds/networking.istio.io_workloadentries.yaml
  chart/crds/networking.istio.io_workloadgroups.yaml
  chart/crds/sailoperator.io_istiorevisions.yaml
  chart/crds/sailoperator.io_istios.yaml
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
  docs/api-reference/sailoperator.io.md
  go.mod
  go.sum
Labels: size/L

#835 [release-1.26] Adding replaces and skipRange to CSV
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/templates/olm/clusterserviceversion.yaml
  chart/values.yaml
Labels: size/XS

#836 Update the operator description as it's no longer experimental
  bundle/manifests/sailoperator.clusterserviceversion.yaml
  chart/values.yaml
Labels: size/S

#842 Skip succeeded
  controllers/istiorevision/istiorevision_controller.go
  controllers/istiorevision/istiorevision_controller_test.go
  controllers/istiorevisiontag/istiorevisiontag_controller.go
Labels: ok-to-test, size/S

#849 enhancements: use issue ID's as SEP numbers
  enhancements/SEP1-enhancement-process.md
Labels: size/XS

#852 Fix issue 851: wrong behaviour in ApplyVendorDefaults
  pkg/istiovalues/vendor_defaults.go
  pkg/istiovalues/vendor_defaults_test.go
Labels: size/M

#853 Add misspell to do basic spell validation in our docs
  Makefile.core.mk
  docs/README.md
  docs/common/istio-ambient-waypoint.md
  docs/guidelines/guidelines.md
  tests/documentation_tests/README-runme.md
  tools/update_deps.sh
Labels: enhancement, size/S

#832 Add KEEP_ON_FAILURE flag to e2e kind tests
  Makefile.core.mk
  tests/e2e/README.md
  tests/e2e/ambient/ambient_suite_test.go
  tests/e2e/ambient/ambient_test.go
  tests/e2e/controlplane/control_plane_suite_test.go
  tests/e2e/controlplane/control_plane_test.go
  tests/e2e/controlplane/control_plane_update_test.go
  tests/e2e/dualstack/dualstack_suite_test.go
  tests/e2e/dualstack/dualstack_test.go
  tests/e2e/integ-suite-kind.sh
  tests/e2e/multicluster/multicluster_externalcontrolplane_test.go
  tests/e2e/multicluster/multicluster_multiprimary_test.go
  tests/e2e/multicluster/multicluster_primaryremote_test.go
  tests/e2e/multicluster/multicluster_suite_test.go
  tests/e2e/multicontrolplane/multi_control_plane_suite_test.go
  tests/e2e/multicontrolplane/multi_control_plane_test.go
  tests/e2e/operator/operator_install_test.go
  tests/e2e/operator/operator_suite_test.go
Labels: enhancement, size/L
